.codecov.yml
.github/workflows/tests.yml
CMakeLists.txt
README.md
setup.cfg
tests/test_sourcefile.py
transformations/tests/test_cloudsc.py

Opening this PR to test the workflow and eventually enable Github Actions.

Github workflow to run code checks and pytest

---

.github/workflows/documentation.yml
.github/workflows/documentation_clean-up.yml

Documentation: Separate clean-up action and comment only on PR

---

loki/build/compiler.py
loki/bulk/scheduler.py
loki/transform/transform_hoist_variables.py
tests/sources/projHoist/module/driver_mod.f90
tests/sources/projHoist/module/subroutines_mod.f90
tests/test_transform_hoist_variables.py

fix and extension of the generic hoist variables functionality

Transform hoist variables: disable subroutines, minor fix regarding string comparison

---

transformations/tests/test_single_column_coalesced.py
transformations/transformations/single_column_coalesced.py

Small bug fixes for the SCC transformation to fix issues #20, #21 and #23.

SCC transformation bug fixes

---

loki/analyse/analyse_dataflow.py
tests/test_analyse_dataflow.py

Bug fixes to the dataflow analysis module including:
- Correct handling of interface blocks
- Removal of loop variable symbol from `live` set in while loops
- Grouping of bodies in multi-conditional nodes preserved, meaning IR can now be correctly reconstructed after dataflow analysis pass

Dataflow analysis bug fixes

---

loki/transform/dependency_transform.py
tests/test_transformation.py

The Fortran standard mandates that `USE` statements should appear before `IMPLICIT NONE` but header includes and interface blocks should appear after it. So when the dependency transform finds header includes after `IMPLICIT NONE` and replaces them in-place with a `USE SOME_MOD` without reordering, we can run into problems.

Fix order of `USE` statements and `IMPLICIT NONE`

---

transformations/tests/test_pool_allocator.py
transformations/transformations/pool_allocator.py

A few small fixes required to run the pool allocator transformation on ecWam physics. Performance is great out of the box! (performance discussed in more detail in the JIRA story DE-757).

Changes needed to run pool allocator transformation on ecWam physics

---

transformations/tests/test_single_column_coalesced.py
transformations/transformations/single_column_coalesced.py

Pretty much what it says on the tin. This feature was untested and triggered a few small bugs in the regression suite. This PR therefore adds a dedicated test and fixes the respective issues.

SCC: Test and small bug fixes for `resolve_masked_statement`

---

codecov.yml
setup.cfg

Depend on pydantic<2.0

---

.github/workflows/regression_tests.yml
transformations/tests/conftest.py
transformations/tests/test_cloudsc.py
transformations/tests/test_ecwam.py

This PR tries to add ecWam regression tests to the Loki CI suite.

Add ecWam regression tests

---

.github/workflows/documentation.yml

Somehow I failed to create a separate CI step to upload documentation after merging PRs, which is fixed by this.

Hotfix: Upload documentation to Sites for main branch

---

loki/transform/transform_hoist_variables.py
scripts/loki_transform.py
tests/test_transform_hoist_variables.py
transformations/tests/test_single_column_coalesced.py
transformations/transformations/single_column_coalesced.py

Hoist variables as `kwargs` (optionally)

SCC-HOIST: Hoist variables as `kwargs` (optionally)

---

loki/backend/cgen.py
tests/test_transpile.py

allow transpilation of 
```fortran
select case (...)
...
end select
```

`cgen`: multiconditional/switch/select case statement

---

transformations/tests/test_pool_allocator.py
transformations/transformations/pool_allocator.py

… pointers but which works on Cray + AMD
Some problems with OMNI related to the unit tests ...

Alternative stack/pool allocator implementation based on Cray pointers compatible with Cray+AMD stack

---

loki/backend/fgen.py
loki/frontend/fparser.py
loki/frontend/ofp.py
loki/frontend/omni.py
loki/ir/nodes.py
loki/ir/tests/test_control_flow.py

This pull request adds support of the FORALL statement and construct: [Intel Developer Reference - FORALL](https://www.intel.com/content/www/us/en/docs/fortran-compiler/developer-guide-reference/2024-0/forall.html). Adding the FORALL support has been mentioned in #117.
I tried to mimic your coding style as much as possible. I am looking forward to your review!

Add support of the FORALL statement and construct (fparser/fgen)

---

loki/batch/tests/test_scheduler.py

Apologies, a Linter check failure crept into main. This fixes the failing check.

Fix Linter warning

---

loki/transformations/pool_allocator.py
loki/transformations/tests/test_pool_allocator.py

Filter out unused vars used to rely on dataflow_analysis only putting temporaries on the stack that are defined/written to.
However, there exist some cases where temporaries are only read and it is not the responsibility of this transformation to decide whether that is reasonable.
With this only unused temporaries are not put on the stack, but all other are put on the stack disregarding whether they are written to or only read.

PoolAllocator: revise stack creation for 'read-only' temporaries

---

loki/batch/scheduler.py
loki/batch/sgraph.py
loki/batch/tests/test_scheduler.py
loki/transformations/block_index_transformations.py
loki/transformations/data_offload/global_var.py
loki/transformations/dependency.py
loki/transformations/hoist_variables.py
loki/transformations/parametrise.py
loki/transformations/pool_allocator.py
loki/transformations/raw_stack_allocator.py
loki/transformations/single_column/tests/test_scc_hoist.py
loki/transformations/tests/test_transform_derived_types.py
loki/transformations/transform_derived_types.py
loki/transformations/transpile/fortran_c.py

instead of successors, pass the subgraph/subtree to transformations, the subgraph can then be used to derive successors

transformations getting subgraph instead of successors from scheduler

---

loki/transformations/inline/constants.py
loki/transformations/inline/tests/test_constants.py

especially regarding float and logical literals.

improve 'inline_constant_parameters' functionality

---

loki/transformations/parametrise.py
loki/transformations/tests/test_parametrise.py

and assigned a constant value.
**Not really sophisticated, however, this will eventually be superseded by some kind of constant propagation anyway**
E.g.
```fortran
integer, intent(in) :: invar
integer, intent(out) :: ret
integer, parameter :: param = 1
integer :: a, b, c, d
real :: x, y, z
logical :: l1, l2, l3
ret = 0
x = 3.5
y = invar * 2.0
z = 4.5 + 3.5
a = ret
b = 10
c = invar*invar
l1 = .false.
l3 = .true.
if (c .gt. 0) then
l2 = .true.
else
l2 = .false.
endif
```
to 
```fortran
INTEGER, INTENT(IN) :: invar
INTEGER, INTENT(OUT) :: ret
INTEGER, PARAMETER :: param = 1
INTEGER :: a, c, d
INTEGER, PARAMETER :: b = 10
REAL :: y
REAL, PARAMETER :: x = 3.5
REAL, PARAMETER :: z = 4.5 + 3.5
LOGICAL :: l2
LOGICAL, PARAMETER :: l1 = .false.
LOGICAL, PARAMETER :: l3 = .true.
ret = 0
y = …
```

Utility to parametrise those scalars which are only written to once

---

loki/transformations/single_column/hoist.py
loki/transformations/single_column/tests/test_scc_hoist.py
loki/transformations/tests/test_utilities.py
loki/transformations/utilities.py

necessary to enable SCC-HOIST for ecphys

new utility: 'substitute_variables_for_definitions'

---

loki/transformations/block_index_transformations.py
loki/transformations/tests/test_block_index_inject.py

A small PR that:
- Adds an option in the `InjectBlockIndexTransformation` to specify arrays that should be forcibly injected via `force_inject_array`. This is primarily aimed at sequence associated arguments that we can't fix in source
- The driver layer is also also enriched with the dummy `FIELD_RANKSUFF_ARRAY` type definitions in the `BlockViewToFieldView` transformation.

Add `force_inject_arrays` option and also enrich the driver in `BlockViewToFieldView` transformation

---

loki/tests/test_subroutine.py

A small housekeeping PR that aims to tidy up `test_subroutine.py` one of the older parts of the code base. This paves the way for some TLC further down the road.
For this we do:
* Remove JIT compilation from some of the simpler tests and explicitly test internal properties of the generated object. Some JIT tests are left that often trigger when frontend-backend pairs disagree, but overall throughput is improved by this
* Merge several tests that deal with variables and argument handling
* Enabled OMNI for all tests by providing header info and fixing tests that are preempted by OMNI's parameter resolution.
And finally, the partial removal of JIT testing speeds-up the respective test quite a bit. 😉

Subroutine: Clean up subroutine tests and enable OMNI

---

loki/ir/pragma_utils.py
loki/ir/tests/test_pragma_utils.py

A simple in-place transformer that updates the content of pragmas based on a given string map.

`SubstitutePragmaStrings` transformer

---

CMakeLists.txt
cmake/loki_python_macros.cmake
loki/tests/test_cmake.py

A small PR to re-enable editable CMake-driven builds.

Restore editable pip installation in CMake builds

---

loki/transformations/single_column/scc.py
loki/transformations/temporaries/__init__.py
loki/transformations/temporaries/stack_allocator.py
loki/transformations/temporaries/tests/test_stack_allocator.py
loki/transformations/tests/test_stack_allocator.py

Refactored `TemporariesRawStackTransformation` and implemented:
* another variant of the "raw stack"/direct indexing
* a stack based on Fortran pointers
Tested with ecwam.

New stack variants: raw/direct indexing and based on Fortran pointers

---

loki/transformations/single_column/base.py
loki/transformations/single_column/tests/test_scc.py
loki/transformations/utilities.py

which is important for SCC trafos ...
The SCC-trafo-family is currently not horizontal-index-alias-aware. E.g., marking horizontal loops only takes the first value of `horizontal.indices` being `horizontal.index` into account. While this could be easily fixed in the vector trafo it becomes more cumbersome for seq trafos. That's why I'd propose this solution (at least for now).

allow to rename (horizontal) index aliases

---

loki/transformations/data_offload/field_offload.py
loki/transformations/loop_blocking.py
loki/transformations/tests/test_loop_blocking.py

A suggestion of how to work around the opaque transformer pattern in #560

Field API loop blocking: partial rebuild and return the region.

---

loki/transformations/single_column/hoist.py
loki/transformations/single_column/tests/test_scc_hoist.py

SCC-HOIST insert 'create pragma' at location-pragma if available (`loki stack-insert`) for now.
In order to improve profiles ...

SCC-HOIST insert create pragma at pragma if available

---

loki/transformations/temporaries/hoist_variables.py

make sure call.routine is not BasicType.DEFERRED.
As discussed offline: suboptimal since I wasn't able to recreate the problem in the Loki tests, since it seems to be a very special case related to inlining a function (and not inlining it in the same module since it has array arguments ...). However, necessary for ecphys to get the seq trafos to work.

HoistVariablesAnalysis and Transformation fix
