- AUTHORS.md
- docs/source/backends.rst
- loki/backend/__init__.py
- loki/backend/cufgen.py
- loki/expression/symbols.py
- loki/ir.py
- loki/program_unit.py
- loki/sourcefile.py
- tests/test_cufgen.py
* the thread index for each dimension starts at one
* kernel invocation: `kernel<<<grid size, thread block size>>>`
* `call kernel<<<grid,block[,bytes][,streamid]>>>(arg1,arg2,...)`
* e.g. using the `dim3` derived type: `type(dim3) =:: blocks, threads`
* `blocks = dim3(n/256, n/16, 1)`, `threads = dim3(16, 16, 1)`  
* device subprograms are not allowed to have the `SAVE` attribute or with data initialization
| subroutine/function qualifier | description |
| ----------------------------- | ----------- |
| `attributes(host)` | to be executed on the host |
| `attributes(global)` | to be executed on the device, called using a kernel call | 
| `attributes(device)` | to be executed on the device, called from a subprogram with `global` or `device` attribute | 
| `attributes(host,device)` | …
> Cuda Fortran (CUF) backend implementation including tests

- .github/workflows/documentation.yml
Remaining CI item was auto-generating and uploading documentation. Not entirely sure this workflow does what it is supposed to do, but it generates documentation for pull request branches and should hopefully do the same for main after merging - and ideally clean-up the pr documentation files.
As a courtesy, the action even prints the link to the generated documentation in the PR ;-)
> Github actions workflow for documentation

- loki/backend/fgen.py
- loki/expression/mappers.py
- loki/expression/symbols.py
- loki/frontend/fparser.py
- loki/frontend/ofp.py
- loki/frontend/omni.py
- tests/test_expression.py
- tests/test_frontends.py
This expands the support for array constructors, in particular `implied-do` format and with type-spec. They had not been handled gracefully before. Implemented for OMNI and fparser, OFP seemed too silly.
Piggy-backed is more sane handling of `PROGRAM` blocks - i.e., printing an error and bailing out. Behaviour was different between frontends before, some treating them as subroutines and others skipping over them. It shouldn't be terribly hard to add an implementation of `ProgramUnit` for that but until we do, we should gracefully fail or ignore that node rather than have some scrambled-together half-representation (since this has confused users before).
> Implied-do support and error for `PROGRAM`

- loki/transform/transform_inline.py
- tests/test_transform_inline.py
After internal constant replacement, any declarations that now only contain literals need to be removed.
Many thanks to @MichaelSt98 for finding this bug and providing the MFE. This should solve issue #8 .
> TransformInline: Fix internal replacement by removing defunct decls

- setup.cfg
See https://github.com/jameskermode/f90wrap/issues/175
NumPy 1.24 ships with "new f2py features and fixes": https://numpy.org/doc/stable/release/1.24.0-notes.html
This requirement can be relaxed once f90wrap has caught up.
> Numpy<1.24 due to f90wrap incompatibility

- docs/source/transform.rst
- loki/frontend/omni.py
- loki/transform/__init__.py
- loki/transform/transform_parametrise.py
- tests/sources/projParametrise/parametrise.f90
- tests/test_transform_parametrise.py
**Probably best explained using an example** (same code used for the unit tests):
<details>
<summary>Source code/Starting point</summary>
```fortran
module parametrise
implicit none
contains
subroutine stop_execution(msg)
character(200), INTENT(IN) :: msg
PRINT *, msg
stop 1
end subroutine stop_execution
subroutine driver(a, b, c, d)
integer, intent(inout) :: a, b, d(b)
integer, intent(inout) :: c(a, b)
real :: x, y
call kernel1(a, b, c)
call kernel2(a, b, d)
call kernel1(a, b, c)
end subroutine driver
subroutine another_driver(a, b, c)
integer, intent(in) :: a
integer, intent(in) :: b
integer, intent(inout) :: c(a, b)
real :: x(a)
call kernel1(a, b, c)
end subroutine another_driver
subroutine kernel1(a, b, c)
integer, intent(in) :: a
integer, intent(in) :: b
integer, intent(inout) :: …
```
> Transformation: parametrise

- .github/workflows/documentation.yml
- .github/workflows/documentation_clean-up.yml
This changes the way the documentation comment is provided, to avoid these duplicate messages.
Also another stab at the cleanup after merging, but that one we'll know only after merging.
> Different way of creating documentation comment

- docs/source/transform.rst
- loki/transform/transform_utilities.py
- tests/test_transform_utilities.py
* **single variable declaration** for specific variables via: `single_variable_declaration(routine, variables=())`
```fortran
subroutine foo(a, x, y)
integer, intent(in) :: a
real, intent(inout):: x(a), y(a, a)
integer :: i1, i2, i3, i4
real :: r1, r2, r3, r4
x = a
y = a
end subroutine foo
```
via `single_variable_declaration(routine=routine, variables=('y', 'i1', 'i3', 'r1', 'r2', 'r3', 'r4'))` to
```fortran
SUBROUTINE foo (a, x, y)
INTEGER, INTENT(IN) :: a
REAL, INTENT(INOUT) :: x(a)
REAL, INTENT(INOUT) :: y(a, a)
INTEGER :: i2, i4
INTEGER :: i1
INTEGER :: i3
REAL :: r1
REAL :: r2
REAL :: r3
REAL :: r4
x = a
y = a
END SUBROUTINE foo
```
________
* **single variable declarations** for subroutines: `single_variable_declarations(routine, strict=True)`
```fortran
subroutine foo(a, x, y) …
```
> Transform utilities: single variable declaration

- loki/tools/util.py
- loki/transform/transform_array_indexing.py
- loki/transform/transform_region.py
- tests/test_symbolic.py
- tests/test_transform_array_indexing.py
- tests/test_types.py
- transformations/transformations/single_column_coalesced.py
This PR creates an internal array transformation to demote individual array dimensions from a list of array variables within a routine. This was previously done in SCC via a custom utility, which we have now generalized and internalised to the core package, including the respective tests. 
As an added bonus, the new routine is now also capable of honouring `DIMENSION` keywords, and will adjust the respective `VariableDeclaration` node accordingly. This should address issue #19 .
> Internalize array demotion transform

- loki/frontend/omni.py
- tests/test_frontends.py
in order to have unique nodes e.g. call statements to the same subroutine ...
which solves some problems e.g. regarding transformer with mapper/dictionary entries which would otherwise be overwritten as the nodes e.g. subroutines are not distinguishable.
> Fixing OMNI get_source()

- loki/__init__.py
- loki/backend/cgen.py
- loki/backend/fgen.py
- loki/backend/maxgen.py
- loki/backend/pygen.py
- loki/expression/mappers.py
- loki/expression/symbols.py
- loki/frontend/fparser.py
- loki/frontend/ofp.py
- loki/frontend/omni.py
- loki/subroutine.py
- loki/tools/strings.py
- loki/tools/util.py
- scripts/loki_transform.py
- tests/test_derived_types.py
- tests/test_expression.py
- tests/test_fgen.py
- tests/test_subroutine.py
A bunch of bug fixes I collected along the way, filing them as a collective PR. Namely the following things are fixed:
- Formatting of `DATA` declaration nodes in fgen backend
- A fix for formatting of long literal lists (or more generally, long lines with nested `JoinableStringList`s): These should now wrap gracefully and produce well-formated line breaks, whereas they would before wrap lines and then indent them, which would make it necessary to break the lines again, leading to all kinds of havoc.
- Newly added support for subroutine suffixes (fixing `BIND` attribute and adding support for `RESULT`)
- There were two bugs in our handling of inline calls with keyword-arguments to type-bound procedures and calls to type-bound procedures declared on array members of a derived type
- A new …
> Tour de bug

- loki/__init__.py
- loki/backend/cgen.py
- loki/backend/fgen.py
- loki/backend/maxgen.py
- loki/backend/pygen.py
- loki/bulk/item.py
- loki/bulk/scheduler.py
- loki/expression/mappers.py
- loki/expression/symbols.py
- loki/frontend/fparser.py
- loki/frontend/ofp.py
- loki/frontend/omni.py
- loki/sourcefile.py
- loki/subroutine.py
- loki/tools/strings.py
- loki/tools/util.py
- scripts/loki_transform.py
- tests/test_derived_types.py
- tests/test_expression.py
- tests/test_fgen.py
- tests/test_modules.py
- tests/test_scheduler.py
- tests/test_subroutine.py
Note: This is based on #18, so review only after that one is merged to reduce diff volume.
With #17 we parse files now in the correct order to theoretically resolve all dependencies right away, thus making manual enrichment essentially superfluous. However, for this to take effect, we have to provide the already parsed program units as `definitions` to `make_complete`, which is added in this PR.
Although it should allow to entirely retire the `_enrich` step in the Scheduler, I have kept it for the moment to avoid fallout in edge cases where this doesn't work for some reason. It works on ecrad, though.
Accompanied with this are tests for nested derived types, where intermediate type definitions can only be resolved via this enrichment method.
With this in place, I have hit a situation in …
> Enrichment during parsing

- loki/bulk/item.py
- loki/frontend/ofp.py
- loki/frontend/regex.py
- tests/conftest.py
- tests/test_frontends.py
- tests/test_interfaces.py
- tests/test_subroutine.py
The purpose of this is to fix the regex frontend bug reported in #26. Solution is to explicitly match interface blocks in the subroutine pattern, thus shortcutting any contained subroutine declarations.
In the process I had already developed a more sophisticated pattern for matching interface blocks. We may need this eventually to resolve #31.
> Fix Regex pattern for subroutines to account for interfaces (fix #26)

- loki/bulk/item.py
- loki/transform/dependency_transform.py
- tests/test_scheduler.py
Two little bugfixes/enhancements for the Scheduler:
1. Resolve a case-sensitivity issue in `Item.qualify_names`
2. Remove duplicates from `Item.children`
Two little fixes for the dependency injection transformation:
1. Canonical basename needs to look for the suffix via `rindex` to avoid aliasing problems (e.g., when looking for `_mod` in `some_model_thing_mod`).
2. Calls to contained member routines can be ignored.
> Minor scheduler and dependency injection bugfixes

- loki/expression/expr_visitors.py
- loki/expression/mappers.py
- loki/expression/symbols.py
- loki/transform/fortran_c_transform.py
- loki/transform/fortran_python_transform.py
- loki/transform/transform_associates.py
- loki/transform/transform_utilities.py
- tests/test_expression.py
- tests/test_pygen.py
- tests/test_transform_utilities.py
- transformations/transformations/single_column_claw.py
As discussed offline, this fixes the infinite recursion issue when we have expression maps like `{var: var + 1}`. Solution is to remove the recursion on the replaced node and rather have a dedicated utility that allows applying that recursion to the expression map before carrying out the substitution.
@MichaelSt98 could you please let me know if this fixes your issue?
> Fix infinite recursion in SubstituteExpression

- .github/workflows/tests.yml
- install
IBM decided to break Ant because they changed hostnames for the NetRexx dependency download. Fixed in the install script.
Took the opportunity to also take care of fixing the permissions problem introduced with a recent venv update when running install script again.
Finally, add some retries to the apt-get commands in the Github actions workflow as that mirror has been flaky in the past.
> Fix installation

- loki/backend/pygen.py
- loki/build/builder.py
- loki/transform/fortran_python_transform.py
- loki/transform/transform_utilities.py
- tests/test_pygen.py
- tests/test_sdfg.py
A small collection of fixes for the Python backend that brings the full CLOUDSC back to validating. I've added a few internal test extensions, but have probably missed a few, so please feel free to request more. CLOUDSC @ Python is not yet part of the CI cycle, so internal testing is paramount.
A few nuggets:
* Better way of ensuring dynamic kernel loading in the tests
* No longer replicate `Subroutine` object as part of F2Py transformation
* Fixed downcasing and added support for statement functions (yes!) and inline calls
* Extended line length limit, since automatic line-breaks work different for Python
* Extended intrinsic handling to include exp/sqrt/sign (the latter works differently, so somewhat cumbersome!)
* Allow explicitly triggering / overriding the index-inversion, as this is …
> Various Pygen-backend fixes

- example/02_working_with_the_ir.ipynb
- loki/analyse/analyse_dataflow.py
- loki/frontend/fparser.py
- loki/frontend/ofp.py
- loki/frontend/preprocessing.py
- loki/frontend/regex.py
- loki/frontend/util.py
- loki/ir.py
- loki/program_unit.py
- loki/scope.py
- loki/transform/dependency_transform.py
- loki/transform/fortran_c_transform.py
- loki/visitors/transform.py
- setup.cfg
- tests/test_cufgen.py
- tests/test_visitor.py
- transformations/transformations/argument_shape.py
- transformations/transformations/scc_cuf.py
- transformations/transformations/single_column_claw.py
- transformations/transformations/single_column_coalesced.py
_Note: This is part 1 of a double-header, which is first concerned with changing the definition and constructor usage of regular IR nodes. Part 2 will specifically focus on the constructor usage of `Scope` objects and expand the change presented here to `ScopedNode`s._
The core rationale behind this change is the fact that we currently use a lot of monkey-patching and hidden magic functions in our IR node definition to enforce pseudo-immutability. However, with Python 3.7+, dataclasses have been introduced that can be used to natively express all these concepts (immutable attributes; dict-like comparison; hashes based select attributes, ...) including the ability to declare an object `frozen=True` and thus prevent direct regular-style updates to the object. We can, however, keep our …
> IR: Use frozen dataclasses to enforce immutablity - Part 1

- loki/bulk/item.py
- loki/frontend/regex.py
- loki/sourcefile.py
- loki/transform/dependency_transform.py
- tests/sources/projInlineCalls/double_real.F90
- tests/sources/projInlineCalls/driver.F90
- tests/test_frontends.py
- tests/test_scheduler.py
- tests/test_transformation.py
One of the recommended ways of declaring inline function calls is via an explicit interface. This PR adds inline function calls declared via an explicit interface as scheduler dependencies. The more modern way of declaring inline function calls is to wrap them in a module and use module imports. Adding this functionality requires a larger update to the scheduler, and this PR is being prepared.
> Add inline function calls as scheduler dependencies

- transformations/tests/test_single_column_coalesced.py
- transformations/transformations/single_column_coalesced.py
Small bug fix in scc-hoist that ensure that a driver loop with more than one call to kernel routines hoists argument for all of them. The bug was simply cause by lazily using the loop to find and adjust the outer block loop with the loop over all candidate calls. The respective test has been extended in place to capture the corner case that tripped this in CLOUDSC2.
As a small bonus, I've also added a log line that prints out the variables hoisted for each driver call, which should not be too polluting in practical cases.
> Fix multi-call hoisting in scc-hoist and extend test

- tests/test_derived_types.py
- tests/test_expression.py
Modified `test_derived_type_linked_list` to iterate to `min(1000, getrecursionlimit()-100)`.
On my system, `getrecursionlimit()` returned 1000. I set 100 as a buffer somewhat arbitrarily. 50 was not enough.
Changed the boz test code to be compliant with the Fortran standard. gfortran 12 refused to compile and looks like `n1 = B'00000'` has not been acceptable since gfortran 10.
> Limited recursion and made boz code gfortran compliant

- loki/bulk/item.py
- tests/test_scheduler.py
One of my recent PRs added the ability to include inline function calls as scheduler dependencies if they are defined in an explicit interface. A pretty nasty bug went unnoticed; if the calling subroutine is part of a module, it will add any procedure interfaces defined in that module as a child of the subroutine. This is a very small PR to fix that bug and test for it.
> Procedure interface scheduler bug fix

- loki/expression/expr_visitors.py
- loki/expression/mappers.py
- loki/frontend/fparser.py
- loki/frontend/ofp.py
- loki/frontend/util.py
- loki/ir.py
- loki/transform/transform_associates.py
- loki/visitors/transform.py
- tests/test_control_flow.py
- tests/test_derived_types.py
- tests/test_expression.py
- tests/test_sourcefile.py
- tests/test_subroutine.py
_Note: This sits on top of #44_
I'm filing this separately because it contributes a significant behaviour change for the `SubstituteExpressions` visitor, which I consider to be sensible but that might require extra testing to make sure it doesn't break behaviour in (untested) edge cases.
In a few places, we ran into infinite recursion in the `AttachScopes` visitor (although it's not specific to that one, it's just the first to be encountered within the frontends), more specifically, if a declared variable is being used in one of the definining attributes. Encountered examples include:
* the initializer expression, e.g. `REAL(KIND=JPRB), PARAMETER :: ZEXPLIMIT = LOG(HUGE(ZEXPLIMIT))`
* the allocation dimensions (which are injected as `shape` in the Loki IR), e.g.: …
> Additional fixes for IR

- loki/transform/transform_parametrise.py
- loki/transform/transformation.py
- tests/test_transformation.py
- transformations/transformations/scc_cuf.py
Due to some unfortunate nesting, we are currently calling excessively often `rescope_symbols` after a transformation.
This is because `post_apply` was called for every subroutine and every module to which a transformation was applied, even if the actual transformation only implements a handler for one of them.
Out of caution, we had put a `rescope_symbols()` call into this `post_apply` method to catch some of the more subtle scope abuse. However, it seems that most transformations are actually fairly good in avoiding scoping errors, as tests pass even without that.
Now, either already at that time or slightly after, the `rescope_symbols()` call has learned to be properly recursive, i.e. also fix scopes for its member routines if called on a subroutine or module. This meant an abundantly …
> Make rescoping in post_apply optional

- loki/transform/dependency_transform.py
- tests/test_transformation.py
The mechanism in the dependency transform to replace a subroutine interface with a module import relied on the subroutine name in the interface block being lower-case. This is now fixed, along with an update to the relevant test.
> Bug fix in dependency transform for routines declared using explicit interface

- loki/bulk/item.py
- loki/bulk/scheduler.py
- loki/frontend/omni.py
- loki/frontend/regex.py
- loki/subroutine.py
- tests/test_frontends.py
- tests/test_scheduler.py
- tests/test_subroutine.py
A set of Scheduler changes aimed at enhancing the capabilities when working with derived types and dependencies from typebound procedure calls.
* When handing successors for an `Item` to a transformation, it follows the indirection of typebound procedures and yields the actual subroutine items in addition to the type binding
* In addition to enriching calls, a new `enrich_types` method provides type annotation for derived types after the initial parse
* A new `add_dependencies` method allows to introduce additional dependencies to an existing Scheduler graph. This may become useful in multiple situations in the future. I am using this to post-hoc introduce dependencies due to inline calls via a bespoke transformation that I will file as a separate PR. This includes a new mechanism to …
> Scheduler enhancements for dealing with derived types

- transformations/tests/test_utility_routines.py
- transformations/transformations/utility_routines.py
The dangling variables and imports make the compiler vomit out a ton of warnings. This will remove those as well as the calls to DR_HOOK
> Remove unused import and variable from hook

- loki/subroutine.py
- tests/test_subroutine.py
We were dropping arrays due to faulty comparison with array symbols; instead we should only test against array name.
This addresses issue #59. Many thanks to @JoeffreyLegaux for reporting and suggesting the fix.
> Subroutine: Fix array declarations in interface generation

- loki/bulk/item.py
- loki/bulk/scheduler.py
- loki/frontend/regex.py
- tests/sources/projInlineCalls/driver.F90
- tests/sources/projInlineCalls/some_module.F90
- tests/test_frontends.py
- tests/test_scheduler.py
Applying Loki transformations to more complex control flows requires generating GPU offload instructions for global (module) variable imports in an automated way. To write these transformations, we first need to extend the definition of scheduler dependencies to also include global variable imports.
This PR addresses the latter, and tries to provide a clean way to add global variable imports as scheduler dependencies. Importantly, the default behaviour remains unchanged; module imports are not added as dependencies unless explicitly stated in the scheduler config. Therefore existing scheduler workflows should not be affected.
Finally, this will likely have some conflicts with #50, and so a rebase is needed once that is merged.
NB: This now relies on a bug-fix in #68.
> Add module imports as scheduler dependencies

- cmake/loki_transform.cmake
- scripts/loki_transform.py
This allows more easily to short-circuit OpenACC insertion by setting `DIRECTIVE none` in the CMake wrapper macros. No additional tests are added, as this primarily is triggered via large regression tests, and most useful for full IFS / EC-physics setups
> Loki-transform: Expose "directive" option through script and CMake

- transformations/tests/test_single_column_coalesced.py
- transformations/transformations/single_column_coalesced.py
`acc routine` pragmas should be appended to `Subroutine.spec` rather than prepending to `Subroutine.body`. Although a relatively benign bug, it can cause issues with the pool allocator transformation so I'm filing this bug fix along with updated tests.
> `acc routine` pragmas fix

- loki/expression/symbols.py
- transformations/tests/test_transform_derived_types.py
- transformations/transformations/derived_types.py
~~_Note: This is based on #51._~~
_Update: This is now separated from #51._
A new transformation that allows resolving calls to typebound procedures by replacing them with direct calls to the corresponding routine. For example:
Given a derived type
```f90
TYPE SOME_TYPE
CONTAINS
PROCEDURE :: SOME_ROUTINE => SOME_TYPE_SOME_ROUTINE
END TYPE SOME_TYPE
```
then a call statement
```f90
CALL SOME_TYPE_VAR%SOME_ROUTINE(ARG1, ARG2, KW=KWARG)
```
is replaced by 
```f90
CALL SOME_TYPE_SOME_ROUTINE(SOME_TYPE_VAR, ARG1, ARG2, KW=KWARG)
```
This takes also care of adding the relevant import to the caller. The same is applied also to InlineCalls in expressions. As a side-effect, these calls are identified as additional dependencies and made available after the Transformer pass. These can then be …
> Transformation to resolve calls to typebound procedures

- transformations/tests/test_data_offload.py
- transformations/transformations/data_offload.py
This PR adds support for multiple calls to kernel subroutines in the `DataOffloadTransformation`. This is required for CLOUDSC2, where we need this transformation to correctly place timers to separate compute and data movement timings.
The implementation itself adds a new test, updates the use of tuples and f-strings for code generation, and adds some logic to ensure repeated array arguments used with different intents on the kernel side are classed correctly and only put into one category
> Support for multiple kernel calls in DataOffloadTransformation

- transformations/tests/test_single_column_coalesced.py
- transformations/transformations/single_column_coalesced.py
When no arrays are hoisted, we would still insert empty `!$acc create/delete` pragmas, which is incorrect and invalid.
> SCC-hoist: Add test and fix corner case, where no arrays are hoisted

- loki/bulk/item.py
- loki/bulk/scheduler.py
- loki/module.py
- loki/program_unit.py
- loki/sourcefile.py
- loki/transform/fortran_c_transform.py
- tests/test_derived_types.py
- tests/test_frontends.py
- tests/test_modules.py
- tests/test_nested_types/test_nested_types.py
- tests/test_scheduler.py
- tests/test_types.py
A small utility PR:
On `ProgramUnit` objects, we have various convenience properties: imports, variables, declarations, ...
The naming "convention" so far was, e.g.:
- `.variables`: list of `Variable` symbols declared in the module or subroutine
- `.variable_map`: `CaseInsensitivDict` to map variable names to variable objects
Only exception was `.typedefs`, which returned a mapping rather than the list of typedefs. This PR homogenizes this by introducing `.typedef_map` and making `.typedefs` a list.
> Homogenize access to typedefs and imports in program units

- loki/expression/mappers.py
- loki/frontend/ofp.py
- scripts/loki_transform.py
- transformations/tests/test_pool_allocator.py
- transformations/tests/test_single_column_coalesced.py
- transformations/transformations/__init__.py
- transformations/transformations/pool_allocator.py
Filing this as a draft to provide a platform for discussions on the implementation. It is not ready for merging, yet, but I would appreciate some input on how to proceed.
This is an implementation of a pool allocator (akin to M-F's "stack") that allocates a large scratch space per block on the driver and maps temporary arrays in the kernels to this space. For an example implementation in CLOUDSC, see https://github.com/ecmwf-ifs/dwarf-p-cloudsc/pull/49
It is built on top of a derived type declared in a separate Fortran module [`stack_mod`](https://github.com/ecmwf-ifs/dwarf-p-cloudsc/blob/nabr-scc-stack/src/cloudsc_loki/stack_mod.F90), which should simply be commited to the target code base. Naming is flexible and can also be provided as options to the transformation.
The transformation …
> Pool allocator transformation

- scripts/loki_transform.py
- transformations/tests/test_cloudsc.py
With ecmwf-ifs/dwarf-p-cloudsc#49 merged, we can enable the "stack" variants in the test_cloudsc.py regression tests.
For OMNI, this requires a little fix to normalize the silly range index behaviour.
> Include Stack transformation in CLOUDSC regression testing

- loki/pragma_utils.py
- transformations/tests/test_data_offload.py
`detach_pragma_regions` replaces any `PragmaRegion` node with the following tuple `(region.pragma, region.body, region.pragma_post)`. This nested tuple is unnecessary, and it causes problems with some of the pydantic checks if the original `PragmaRegoin` was nested with a `Conditional` or other `InternalNode`. Here is a small fix with updated tests.
> Pragma regions detach bug fix

- loki/analyse/analyse_dataflow.py
- tests/test_analyse_dataflow.py
The dataflow analysis was missing a `visit_Associate` method. @MichaelSt98 and I both ran into this issue. This is an attempted fix with matching test, please let me know what you think.
> Dataflow associate block fix

- loki/bulk/scheduler.py
- loki/expression/symbols.py
- loki/frontend/fparser.py
- loki/frontend/regex.py
- loki/ir.py
- loki/transform/transform_associates.py
- tests/test_frontends.py
- tests/test_interprocedural_analysis.py
- tests/test_scheduler.py
- tests/test_transform_associates.py
- transformations/transformations/data_offload.py
- transformations/transformations/utility_routines.py
A collection of commits with various minor bugfixes/improvements:
- Add a different colour for import items in the Scheduler's callgraph
- Equip `InlineCall` with the same set of inter-procedural properties as `CallStatement`, with associated testing
- Fix a bug with nested tuples in `Associates` for fparser
- Fix a bug with nested tuples in the `resolve_associates` transformation
- Fix REGEX frontend when square brackets are used in an initialiser list
- Apply `RemoveCallsTransformation` only on Scheduler graph items
- Fix `GlobalVarOffload` to not fail when `trafo_data` is empty for a successor
> Various bugfixes

- loki/transform/build_system_transform.py
- loki/transform/dependency_transform.py
- loki/transform/transform_hoist_variables.py
- loki/transform/transform_parametrise.py
- loki/transform/transformation.py
- tests/sources/projA/module/driverE_mod.f90
- tests/sources/projA/module/kernelE_mod.f90
- tests/test_lint/test_linter.py
- tests/test_lint/test_reporter.py
- tests/test_scheduler.py
- transformations/transformations/data_offload.py
- transformations/transformations/derived_types.py
- transformations/transformations/pool_allocator.py
- transformations/transformations/scc_cuf.py
- transformations/transformations/single_column_coalesced.py
- transformations/transformations/single_column_coalesced_vector.py
Mnay(!) of our transformations require the same entry-point check that the subroutine about to be processed has indeed been requested by the scheduler. This PR moves this check up to the `Transformation` base class and adds a test to check for the most common violation of this. The problem really arrives if we have modules with multiple subroutines, of which only a subset is meant to be transformed.
As this touches the SCC cases, it would be good to run full regression on this. I've verified that it works with the current EC-physics demonstrator case.
> Scheduler: Only apply transformations to requested subroutines 

- cmake/loki_transform.cmake
- loki/transform/dependency_transform.py
- scripts/loki_transform.py
- transformations/tests/test_pool_allocator.py
- transformations/tests/test_single_column_coalesced.py
- transformations/tests/test_utility_routines.py
- transformations/transformations/data_offload.py
- transformations/transformations/pool_allocator.py
- transformations/transformations/single_column_coalesced.py
- transformations/transformations/single_column_coalesced_vector.py
- transformations/transformations/utility_routines.py
For both correctness and performance, the SCC transform needed a few updates before it could be applied to the ecWam physics. With that aim, this branch adds the following features:
- `trim_vector_sections` option to remove scalar assignments from vector loops
- Removal of calls explicitly marked with `!$loki inline` pragmas from separator nodes
- Loki-pragma driven insertion of reduction loops
The companion piece to this PR is the following ecWam branch where similar to CLOUDSC, we use Loki's cmake tools to build a range of transformations: https://github.com/ecmwf-ifs/ecwam/tree/naan-loki-trafo
NB: This is stacked on top of #92.
> SCC updates needed for ecWam

- transformations/tests/test_cloudsc.py
- transformations/tests/test_single_column_coalesced.py
- transformations/transformations/single_column_coalesced.py
- transformations/transformations/single_column_coalesced_wrapper.py
Setting the vector_length directive to the block size has shown to significantly improve performance for NPROMA numbers that don't match the default value of the architecture. This aims to add this directive to the OpenACC directives inserted in the driver as part of the SCC transformations.
For that, it attempts to find any of the `size_expressions` of the horizontal dimension and use that. Note, that this only works with NVIDIA, the Cray compiler will ignore this value if it is not a compile-time constant.
> SCC: Insert vector_length directive into the gang loop

- codecov.yml
Filing this as a separate PR to get input on the level of degradation we should allow. I've gone for 1% per PR, which would easily work for most of the maintenance PRs, where this is the biggest issue. Opinions and comments welcome.
> Loki: Add a 1% code coverage degradation threshold

- .github/workflows/code_checks.yml
- .github/workflows/regression_tests.yml
- .github/workflows/tests.yml
- README.md
- loki/types.py
- setup.cfg
A small change to achieve compatibility with Python 3.11. Reason is that since 3.11, Enum values do get the type of all mixin base classes and because of the composing nature how this is done, the assertion we had there triggered.
See also https://discuss.python.org/t/inconsistent-behavior-with-python-3-11-enum-mixin-class-behavior/24613/4
I had to also use a plain `Enum` with `int` datatype instead of `IntEnum` to retain the original `str`-behaviour. (Changed with PEP 663)
Testing has been expanded to include Python 3.11
> Python 3.11 compatibility

- .codecov.yml
- codecov.yml
Trialling new code coverage settings that are less permissive, more detailed and disable patch testing. Also removes the previous `.codecov.yml` which probably got conflated with the real one.
> Codecov: Remove old config, drop threashold, disable patch checking

- scripts/loki_transform.py
- transformations/tests/test_utility_routines.py
- transformations/transformations/utility_routines.py
This avoids the removal of DrHook calls in the driver layer, which we actually want for benchmarking.
> ECPhys: Add a "kernel-only" option to remove calls

- tests/test_expression.py
This includes testing that string-matching also works for matching against strings, both as keys or items.
> Expressions: Add test for containment behaviour of expressions

- lint_rules/lint_rules/ifs_coding_standards_2011.py
- loki/analyse/analyse_dataflow.py
- loki/expression/operations.py
- loki/expression/symbols.py
- loki/frontend/fparser.py
- loki/frontend/ofp.py
- loki/frontend/omni.py
- loki/frontend/util.py
- loki/visitors/transform.py
- tests/test_source_identity.py
- tests/test_visitor.py
Expression nodes have a `source` attribute, and the smallest unit of source is a source line. Strictly speaking, the `source` property of an expression should be just the expression itself, i.e. smaller than a full-line.
In many instances, the control-flow node `source` can be invalidated but `Expression.source` will still be intact, e.g. after a `Transformer` pass. This can then cause problems when running `fgen` in `conservative=True` mode. When the `fgen` visitor arrives at the `Expression` node in question and finds the `source` property intact, it will simply print `Expression.source` rather than generating Fortran code. Because `Expression.source` points to a full source-code line, incorrect code is generated.
@reuterbal suggested that because we cannot correctly parse the source …
> Remove `ExprMetadataMixin`

- loki/transform/transform_array_indexing.py
- transformations/transformations/single_column_coalesced.py
_Note, this PR stack on top of #124 and should only be reviewed once this is merged._
A small housekeeping PR that homogenises the detailed logging info in Loki-SCC passes (after the removal of the wrappers), and adds some more warnings for "correct, but bad" code constructs that should be resolved in the original source. This includes private array declarations at the "vector" level and wrong ordering of parallel directives (`loop vector` inside `loop seq`).
Please note that the latter requires more advanced features (proper source-level subroutine inlining) that are currently still under development to truly mitigate. In the meantime, removing some of these by hand seems to have small positive effects in ec-physics regression.
> SCC: Better logging and warning for "bad" code constructs 

- loki/bulk/item.py
- loki/bulk/scheduler.py
- loki/frontend/regex.py
- loki/module.py
- loki/program_unit.py
- loki/scope.py
- loki/sourcefile.py
- loki/subroutine.py
- tests/sources/projBatch/headers/header_mod.F90
- tests/sources/projBatch/include/comp2.intfb.h
- tests/sources/projBatch/module/a_mod.F90
- tests/sources/projBatch/module/b_mod.F90
- tests/sources/projBatch/module/other_mod.F90
- tests/sources/projBatch/module/t_mod.F90
- tests/sources/projBatch/module/tt_mod.F90
- tests/sources/projBatch/source/comp1.F90
- tests/sources/projBatch/source/comp2.f90
- tests/sources/projTypeBound/typebound_item.F90
- tests/test_batch.py
- tests/test_frontends.py
I'm filing this in a very rough shape against the scheduler staging development branch because the list of changes is already growing significantly and I want to give you at least a fighting chance to work through them. There is currently also some duplication in the `item.py` file, while the current Scheduler infrastructure still exists, of which substantial amounts are going to become redundant.
I fully intending to clean this up in the subsequent dev-PRs against the staging branch. In particular, proper documentation needs to be added. The downside of this approach is that the final picture is not clearly visible, yet. 
For context, the next steps would be:
1) to swap out the existing callgraph under the Scheduler, and replace this with an SGraph;
2) to add the SFilter view methodology …
> SGraph draft before Scheduler integration

- cmake/loki_transform.cmake
- scripts/loki_transform.py
Unlike the `ecphys` entry point, `loki_transform.py convert` always applies the `DerivedTypeArgumentTransformation`. This PR adds a switch to allow overriding this behaviour (default `True`, as before), and extends the CMake API with a similar override option.
> Make derived argument flattening optional in loki_transform convert

- loki/frontend/fparser.py
- loki/frontend/util.py
- tests/test_subroutine.py
Previously, statement functions (on of the true beauties of the Fortran standard!) have been retro-fitted to the IR after an initial parse, since the FParser frontend cannot distinguish them from regular array accesses without type information. As pointer out in issue #104, the Loki FP frontend can also fall into the trap of getting this wrong by preprending the last stmt function to the subroutine body instead of appending it to the spec.
This PR now fixes the statement function detection by using our internal symbol table to detect them on-the-fly and thus construct them as part of the original parse. This avoids some very(!) costly IR transformations (rebuilds) that we otherwise perform routinely. Since the StmtFunc objects are already in the partial IRs for spec and body, re-shuffling …
> Statement function parsing on-the-fly

- loki/expression/symbols.py
- loki/frontend/fparser.py
- tests/test_expression.py
_Note the problem this PR intends to fix is the underlying problem to the symptoms reported in #128. Many thanks to @rolfhm for providing the MFE that helped triage this._
This PR adds a test and fixes certain corner cases for type updates of symbols via `symbol.clone(type-<...>)`. The key problem is that there were edge-cases where we would preserve existing type info stored in the associated scope of the symbol, if the new type was deemed inadequate. This PR now simplifies this logic and only ignores the incoming type if it is `None`, as we do not allow `None` type info in the symbol table (`BaseType.DEFERRED` signifies unknown types). 
In addition, a test was added that pins down the intended behaviour for plain scalar symbols. In the future this could be extended to procedures etc., …
> Fix type update behaviour in expression clones

- docs/source/visitors.rst
- lint_rules/lint_rules/ifs_coding_standards_2011.py
- lint_rules/tests/test_ifs_coding_standards_2011.py
- loki/expression/expr_visitors.py
- loki/expression/mappers.py
- loki/transform/transform_utilities.py
- tests/test_expression.py
- tests/test_frontends.py
- tests/test_visitor.py
- transformations/transformations/derived_types.py
This fixes the symptom described in #133.
The retrieval function for IR visitors that recurse into expression trees is defined as a static method on the class of each such visitor. While the current way how this is being installed is debatable, it is conceptually correct. However, a later addition allowed to parameterize this retrieval function by providing the option to not recurse to "parents" of expression nodes (the `recurse_to_parent` option). This causes problems, because multiple instances of the same class may then use different variations and consequently change the behaviour of existing objects.
This option relates to the used of derived type member variables, where e.g., a lookup of symbols would then yield, say `a%b%c`, `a%b` and `a` - but return only `a%b%c` if that recursion …
> Expression mappers: Remove recurse_to_parent option and recurse by default

- loki/subroutine.py
- tests/test_subroutine.py
This PR fixes the bug highlighted in #134 (in the presence of an explicit interface, `call.name` still points to symbol defined by interface even after enriching calls).
> Fix for enrich calls bug

- loki/transform/transform_hoist_variables.py
- tests/test_transform_hoist_variables.py
The issue are declarations of multiple temporaries in a single statement, of which not all are hoisted. The hoisted temporaries receive an additional `intent` attribute, which means these need to be declared separately from non-hoisted variables.
This fixes the issue by using the `single_variable_declaration` utility to create separate declarations for hoisted temporaries.
Piggy-backed is a small fix to ensure case-insensitive behaviour in a call lookup, which showed up when using the supplied test.
> Single declarations for hoisted variables in recursive hoist transformation (fixes #143)

- cmake/loki_transform.cmake
- scripts/loki_transform.py
- transformations/tests/test_data_offload.py
- transformations/transformations/data_offload.py
A small update to the `DataOffload` transformation to mark kernel array arguments as true device-pointers and skip address translation via the OpenACC map. This is needed when using the CUDA backend in the new FIELD_API. The new functionality has been tested here: https://github.com/ecmwf-ifs/ecwam/tree/naan-deviceptr.
NB: This is stacked on top of #142.
> Add `DEVICEPTR` annotations to data region in driver loop

- transformations/tests/test_scc_cuf.py
- transformations/transformations/scc_cuf.py
Hotfix for failing transformation of CLOUDSC (see https://github.com/ecmwf-ifs/dwarf-p-cloudsc/actions/runs/6275881222/job/17044373035)
This is fallout from the recent removal of Transformation recursion, where previously the import was injected into the driver module. No tests had been verifying this. Now it is instead added to the driver subroutine and checked in the tests.
> Fix cudafor import in driver for SCC CUF

- AUTHORS.md
- cmake/loki_transform.cmake
- loki/expression/symbols.py
- loki/ir.py
- loki/transform/transform_inline.py
- scripts/loki_transform.py
- tests/test_expression.py
- tests/test_transform_inline.py
- transformations/transformations/single_column_coalesced.py
_Note: I'm filing this early to enable debugging with external use cases. It is entirely likely that I've missed edge cases and would like to weed these out early, if possible. Interested user should feel free to comment here with edge-cases that break this feature._
This PR brings in an initial implementation of an internally supported source-level member subroutine inlining utility that substitutes a call to a member routine (subroutine contained within another subroutine with a shared variable declaration space) with its body. This is then exposed to the SCC-style family of transformations via an option `inline_members`, both via the CMake interfaces and the general `loki_transform.py` head script ("convert" and "ecphys" mode).  
This will perform matching of sub-array argument …
> Member inlining utility transform

- tests/test_frontends.py
- tests/test_subroutine.py
We had seen random failures of CI tests with a segfault, which typically went away when re-running the test. I have tracked this down to the statement functions test, where an uninitialised value was used for the index when writing to an array.
The test has been fixed and the problem hasn't resurfaced so far, hoping this was the root cause.
> Bugfix: Memory error in Statement functions test

- cmake/loki_transform.cmake
- cmake/loki_transform_helpers.cmake
- scripts/loki_transform.py
This refactors the CMake integration of Loki. As this is intended to incorporate the changes in #149 and resolve the outstanding issues in there, this is filed as a PR against that branch.
The following changes are applied:
- A single entry point `loki_transform` is now the default invocation of loki-transform.py, replacing `loki_transform_convert` and `loki_transform_command`. This is also used by `loki_transform_target` to apply the actual transformations.
- The various utility macros to translate arguments of the CMake functions to command-line arguments for loki-transform.py have been consolidated into two routines to parse options and arguments. This is possible because validating arguments is now left purely to the Python layer, i.e., the loki-transform.py script. However, the CMake …
> CMake refactoring for loki_transform

- cmake/loki_transform.cmake
- cmake/loki_transform_helpers.cmake
- scripts/loki_transform.py
Post-hoc fix to an oversight in PR #142. When removing the dedicated `ecphys` entry point, we dropped the argument array shape transformation that is used to replace `:` dimensions with explicitly named dimensions in the surface modules of the code. This PR adds an option (on by default) to the `convert` entry point that re-enables this behaviour.
> Loki_transform: Re-instate argument shape derivation in `convert`

- transformations/tests/test_single_column_coalesced.py
- transformations/transformations/single_column_coalesced.py
- transformations/transformations/single_column_coalesced_vector.py
to apply loop flip, vector and seq annotations at driver level too
* introducing two new Loki pragmas
* `!$loki separator` - for extract vector sections in order to have assignments in the correct position
* `!$loki driver-loop` - for recognising a driver loop without a call in it
> Extend SCC transformation to loops in driver

- AUTHORS.md
- loki/backend/fgen.py
- loki/frontend/ofp.py
- loki/frontend/omni.py
- tests/test_fgen.py
We only stored the `SAVE` attribute for variables with the FP frontend and didn't output it again via `fgen`. This adds a test and fixes the missing behaviour.
Thanks to @quepas for reporting and providing a reproducer and fix.
> Save attribute (fix #164)

- loki/transform/transform_inline.py
- tests/test_transform_inline.py
We want to eliminate the symbols from dummies variables when hoisting the local variables from an inlined member routine to its caller.
The check eliminated symbols from the routine._dummies list, but we rather want the list of memeber._dummies
> bugfix : symbols from the inlined member's dummies were hoisted in the calling routine

- transformations/tests/test_utility_routines.py
- transformations/transformations/utility_routines.py
Main will not call the remove_call and remove_hook on contained routines, resulting in code that does not compile. This PR adds calls on any member routines as well
> Call remove call and remove hook  transformations on contained subroutines

- transformations/tests/test_single_column_coalesced.py
- transformations/transformations/single_column_coalesced_vector.py
This PR is a one-line fix to the vector section trimming within the driver loop. The corresponding test is parametrised to show the effect of vector section trimming.
> Fix vector section trimming in driver loop

- loki/transform/transform_inline.py
- tests/test_transform_inline.py
A small fix the the member inlining utility and accompanying test.
The problem was the wrong use of symbol substitution, which we now face to rescope and rebuild when replicating the body of the child routine to the parent. This would otherwise in-place update associate statements, as they are type definitions, which creates issues for replicated calls, as the same object is used for separate substitutions.
Many thanks to @rolfhm for finding, flagging and triaging the problem and providing the accompanying test case.
> TransformInline: Fix rescoping in expression substitution

- loki/program_unit.py
- loki/subroutine.py
- tests/test_modules.py
- tests/test_subroutine.py
As the title implies, we were indeed not rebuilding nested `ScopedNode` objects in the duplication `Transformer` used for deep-copying (cloning) of  `Subroutine`/`Module` objects. This PR fixes this and adds tests that include nested `ScopedNode` objects (`Associate` for subroutine and `TypeDef` for modules) in the duplicated IR. 
This should fix issue #174.
Many thanks to @JoeffreyLegaux for reporting and providing the reproducer for the subroutine case. I've slightly shortened the example code, but in essence it's the same problem. :wink: Please do confirm that this fixes things as you'd expect.
> Fix deep-cloning of subroutiens and modules (fix #174)

- tests/conftest.py
- sourcefile has a source not a filepath
> Sourcefile does not have a filepath

- loki/transform/transform_inline.py
- tests/test_transform_inline.py
The shadow mapper will only find variables in the declaration and leaves the body unchanged.
I do not understand the need for the `[dl.name for dl in duplicate_locals]` construct though. I would have thought that a `v in duplicate_locals` or `v.name in duplicate_locals` would be sufficient.
> InlineMember: rename duplicate locals in the body

- scripts/loki_transform.py
add `kernel_only=True` to RemoveCallsTransformation to avoid DrHook Calls being removed from driver routines. 
This was part of the `loki_transform.py` `ecphys()` entry point, but not yet part of the `convert()` entry point. Tested with/for ecphys.
> add 'kernel_only=True' to RemoveCallsTransformation

- loki/backend/fgen.py
- loki/frontend/fparser.py
- loki/frontend/regex.py
- tests/test_frontends.py
- tests/test_subroutine.py
This PR adds two small parsing fixes:
- The REGEX frontend can now parse member functions where the result variable has a specified kind
- Statement function result variables are now allowed to share a declaration with other variables
With these changes, Loki can successfully parse the refactored `LAPINEA/LAPINEB` kernels.
> Small parsing fixes

- transformations/tests/test_pool_allocator.py
- transformations/transformations/pool_allocator.py
Added a bit of code to handle range indices in array declarations and modified tests accordingly.
> pool_allocator handles range indices

- example/05_argument_intent_linter.ipynb
- lint_rules/tests/test_debug_rules.py
- loki/bulk/scheduler.py
- loki/frontend/regex.py
- loki/program_unit.py
- loki/subroutine.py
- scripts/loki_transform.py
- tests/test_analyse_dataflow.py
- tests/test_scheduler.py
- tests/test_subroutine.py
- transformations/tests/test_argument_shape.py
- transformations/tests/test_data_offload.py
- transformations/tests/test_single_column.py
- transformations/tests/test_single_column_coalesced.py
Another lift of functionality from the Scheduler overhaul.
This one adds a more generic enrichment process. It is anchored on the following concepts:
1. For anything that is imported via a module import (i.e. `USE`), it is sufficient to look at the import nodes and update the symbol table entries of the symbols listed there (or for all symbols from the remote module if no only list is given). This applies to both, modules and subroutines (we haven't done enrichment for the first before) and also gives us typedef and global variable enrichment.
2. For anything that inherits its type from a parent (e.g., import in the parent module, call in the module procedure), we can compare symbol table entries with the parent's symbol table
3. For `Subroutine`s (the only ones where `CallStatements` can …
> Generic enrichment process

- loki/bulk/item.py
- tests/test_scheduler.py
A very small and pragmatic change that allows us to generically exclude groups of calls from `Scheduler` traversal by using wildcards in the `disable` method. A more robust and generic solution would probably extend wildcard notation to all path/source name resolution mechanisms, but as the `Scheduler` is still being refactored heavily I chose the "quick and easy" option. Opinions and comments very welcome, of course!
> Allow wildcards in `disable` list for scheduler

- loki/bulk/scheduler.py
- loki/lint/linter.py
- loki/transform/build_system_transform.py
- loki/transform/dependency_transform.py
- loki/transform/transform_hoist_variables.py
- loki/transform/transformation.py
- scripts/loki_transform.py
- tests/test_scheduler.py
- tests/test_transform_dependency.py
- tests/test_transform_hoist_variables.py
- transformations/tests/test_argument_shape.py
- transformations/tests/test_global_var_offload.py
- transformations/tests/test_pool_allocator.py
- transformations/tests/test_scc_cuf.py
- transformations/transformations/argument_shape.py
- transformations/transformations/data_offload.py
- transformations/transformations/pool_allocator.py
This PR changes the way we configure the `Scheduler` behaviour for individual `Transformation` passes. Up until now, we rely on the user of a transformation to hand any special iteration properties (reverse graph traversal, program unit recursion, etc.) as run time argument to the scheduler, with no safeguards if the wrong behaviour is requested. 
This PR now changes this, so that `Transformation` objects carry a set of specific flags as class properties (the manifest) that can be overridden in the class definition. So far, this change only moves scheduler traversal behaviour and behaviour specific to `apply(...)` to the manifest, but it can easily be extended to capture other static meta-information, etc. 
In more detail:
* Moved `reverse_traversal`, `traverse_file_graph` and …
> Static Transformation properties (manifest)

- docs/source/transform.rst
- loki/bulk/item.py
- loki/transform/dependency_transform.py
- scripts/loki_transform.py
- tests/test_scheduler.py
- tests/test_transform_dependency.py
The DependencyTransformation is responsible for an increasing number of workarounds and special casing in the scheduler traversals. Part of this has been identified to be related to the fact that two concepts are mixed together here:
1. Renaming of scopes (modules/subroutines get new names, which requires renaming on the caller side)
2. Changing scopes (subroutines get embedded into modules)
This PR splits the two into separate transformation passes but tries to be minimally invasive otherwise. There may undoubtedly be capacity in rewriting some of the transformation logic itself but that can now be a separate change.
The original `strict` mode behaviour is retained by plainly calling the DependencyTransformation, the `module` mode is recovered by applying the new ModuleWrapTransformation …
> Create separate ModuleWrapTransformation from DependencyTransformation

- loki/expression/symbolic.py
- loki/transform/__init__.py
- loki/transform/transform_dead_code.py
- loki/transform/transform_inline.py
- scripts/loki_transform.py
- tests/test_symbolic.py
- tests/test_transform_dead_code.py
- tests/test_transform_inline.py
- transformations/tests/test_single_column_coalesced.py
- transformations/transformations/single_column_coalesced.py
The primary purpose of this PR is to introduce pragma-driven source inlining for Suboutine where `CallStatement` nodes annotated with the `!$loki inline` pragma are replaced by the body of the called routine, with resolved argument mappings. As I developed this on the EC-physics regression suite, I needed to include a few additional utilities that deal with the fallout of the resolution of optional arguments (simplistic logic evaluation in `simplify` and primitive dead code elimination), but these could easily be factored into a separate PR if that is desirable (@reuterbal, please shout!). 
Otherwise, the PR is primarily a refactoring of the procedure inlining utility, where the remapping of a call to the called body is now completely separated from the dealing with local variable …
> Pragma-driven subroutine inlining and associated utilities

- loki/backend/cgen.py
- loki/transform/fortran_c_transform.py
- loki/transform/transform_array_indexing.py
- tests/test_transform_array_indexing.py
- tests/test_transpile.py
**Usable and tested as drop in replacement for the CLOUDSC Loki C transpilation**
* do we want to keep the original *pointer hack* as another option or just replace it?
Convert e.g., 
```fortran
INTEGER, INTENT(INOUT) :: x1(l1)
INTEGER, INTENT(INOUT) :: x2(l2, l1)
INTEGER, INTENT(INOUT) :: x3(l3, l2, l1)
INTEGER, INTENT(INOUT) :: x4(l4, l3, l2, l1)
DO i1=1,l1
x1(i1) = ...
DO i2=1,l2
x2(i2, i1) = ...
DO i3=1,l3
x3(i3, i2, i1) = ...
DO i4=1,l4
x4(i4, i3, i2, i1) = ...
END DO
END DO
END DO
END DO
```
to:
```fortran
INTEGER, INTENT(INOUT) :: x1(l1)
INTEGER, INTENT(INOUT) :: x2(l2*l1)
INTEGER, INTENT(INOUT) :: x3(l3*l2*l1)
INTEGER, INTENT(INOUT) :: x4(l4*l3*l2*l1)
DO i1=1,l1
x1(i1) = ...
DO i2=1,l2
x2(i2 + l2*(i1 + -1)) = ...
DO i3=1,l3
x3(i3 + l3*(i2 + l2*(i1 + -1) + -1)) = ...
DO i4=1,l4 …
```
> introduce 'flatten_arrays()' (to overcome pointer hack)

- loki/transform/transform_inline.py
- tests/test_transform_inline.py
Hello.
This PR fixes a bug in `inline_subroutine_calls`.
Consider the following example (here demonstrating with `inline_member_procedures`, which eventually calls the above):
```
from loki import Sourcefile
from loki.transform import (
inline_member_procedures
)
fcode = """
subroutine outer(klon)
integer :: jg, jlon
integer :: arr(3, 3)
jg = 70000
call inner2()
contains
subroutine inner2()
integer :: jlon, jg 
integer :: arr(3, 3)
do jg=1,3
do jlon=1,3
arr(jlon, jg) = 11 
end do
end do
end subroutine inner2
end subroutine outer
"""
src = Sourcefile.from_source(fcode)
routine = src.routines[0]
inline_member_procedures(routine)
print(routine.to_fortran())
```
On the main branch, this prints:
```
SUBROUTINE outer (klon)
INTEGER :: jg, jlon
INTEGER :: arr(3, 3)
INTEGER :: inner2_jlon, …
```
> Array shadowing bugfix for inliner

- loki/transform/transform_hoist_variables.py
- scripts/loki_transform.py
- transformations/tests/test_single_column_coalesced.py
Hello.
This PR contains two very small changes. I discuss them below.
> Fixes to minor issues related to SCC HOIST

- transformations/tests/test_transform_derived_types.py
- transformations/transformations/derived_types.py
from procedure signatures (via replacing by its members). 
I will almost certainly rely on this for F2LowLevelGPU transformation(s), at least until different/more sophisticated solutions exist. Anyway, I think this is a useful in general. 
Introducing: `all_derived_types : bool, optional`
> Whether to remove all derived types from procedure signatures by
replacing the derived type arguments using its member variables or
only the "relevant" ones, referring to derived types with array
members or nested derived types (default: `False`).
> introduce flag to allow removing all derived types

- cmake/loki_transform.cmake
The re-use of the _PAR prefix means we get aliasing between loki_transform_convert and loki_convert_plan. We fix this by changing the prefix in the outer loki_transform_target.
Please note, this was discussed offline and is exclusively restricted to the CMake layer only, and thus does not come with explicit test coverage. We use this in EC-physics regression, where the use of the `--derive-argument-shape-array` is needed for performance reasons in the surface sub-branches - it's been verified to work there.
> CMake: Fix DERIVE_ARGUMENT_SHAPE_ARRAY and argument handling

- loki/frontend/fparser.py
- loki/frontend/ofp.py
- loki/frontend/regex.py
- loki/ir.py
- loki/lint/linter.py
- loki/module.py
- loki/program_unit.py
- loki/scope.py
- loki/sourcefile.py
- loki/subroutine.py
- tests/sources/projTypeBound/typebound_item.F90
- tests/sources/projTypeBound/typebound_other.F90
- tests/test_derived_types.py
- tests/test_frontends.py
- tests/test_interfaces.py
- tests/test_lint/test_linter.py
- tests/test_modules.py
- tests/test_subroutine.py
- tests/test_transform_dependency.py
This is intended to be the last maintenance PR of small fixes that are lifted from the Scheduler rewrite. Mostly centered around an improved representation of interfaces and recognizing them as an external-facing declaration in modules, and a consistent representation of procedure bindings in the type information of procedure symbols.
It includes also the stubs to perform partial (i.e., only with a subset of patterns) parsing in the REGEX frontend, including (partial) re-parsing.
> Minor fixes to frontends and IR nodes

- transformations/tests/test_pool_allocator.py
- transformations/transformations/pool_allocator.py
Replacing the usage of `stack_mod.F90` or rather a derived type by passing either one integer as stack variable or two if bound checking is activated. 
Tested for CLOUDSC `idem-stack` and `scc-stack` without any changes necessary. However, the `stack_mod.F90` is not necessary anymore. 
________
Thanks @lukasm91 for pointing out that passing the stack via integer(s) is or rather might be beneficial regarding performance in dependence of the hardware, software stack and runtime!
________
> Stack/Pool Allocator: pass stack as integer(s)

- loki/frontend/fparser.py
- loki/frontend/ofp.py
- tests/test_frontends.py
Small bug-fix and test to fix erroneous parsing of multi-line pragmas with missing whitespaces after the keyword. Many thanks for @ecossevin for reporting this (see issue #216).
> Frontend: Fix bug for multi-line pragmas and add short test

- loki/transform/transform_array_indexing.py
- tests/test_transform_array_indexing.py
`normalize_array_shape_and_access()` didn't handle assumed size arrays correctly. 
This is a proposed fix/extension.
> assumed size array handling for 'normalize_array_shape_and_access'

- loki/expression/mappers.py
- tests/test_expression.py
Possibly a solution to issue https://github.com/ecmwf-ifs/loki/issues/182
> Nested derived type bug fix

- loki/backend/cgen.py
- loki/expression/mappers.py
- loki/expression/symbols.py
- loki/transform/fortran_c_transform.py
- tests/test_expression.py
Should be `Dereference(<derived_type>%member)`. However, it would be more correct to have `Dereference(<derived_type>)%member`. But, this won't work unless `Reference`/ `Dereference` get e.g., the following methods:
```py
@property
def name(self):
return self.expression.name
@property
def type(self):
return self.expression.type
@property
def scope(self):
return self.expression.scope
@property
def initial(self):
return self.expression.initial
```
Moreover, the insertion of parentheses is a bit hacky rn ...
**Tested** currently via the *transpile* tests and tested with CLOUDSC Loki C.
___________
**EDIT:**: using the `Dereference(<derived_type>)%member` approach with the above mentioned methods implemented. This seems to be the best solution for now, but it is **experimental** and may be …
> C/C++ De/Reference

- .github/workflows/regression_tests.yml
- loki/transform/fortran_c_transform.py
Nothing more than that. That should allow to run the regression tests (and fail then) even if private repositories are not accessible.
> Github actions: Only load SSH_KEY from secrets if available

- transformations/tests/test_data_offload.py
- transformations/transformations/data_offload.py
Global/Imported variable hoisting.
Convert e.g., 
```fortran
module moduleB
real :: var2
real :: var3
end module moduleB
module moduleC
real :: var4
real :: var5
end module moduleC
subroutine driver()
implicit none
call kernel()
end subroutine driver
subroutine kernel()
use moduleB, only: var2,var3
use moduleC, only: var4,var5
implicit none
var4 = var2
var5 = var3
end subroutine kernel
```
to:
```fortran
module moduleB
real :: var2
real :: var3
end module moduleB
module moduleC
real :: var4
real :: var5
end module moduleC
subroutine driver()
use moduleB, only: var2,var3
use moduleC, only: var4,var5
implicit none
call kernel(var2, var3, var4, var5)
end subroutine driver
subroutine kernel(var2, var3, var4, var5)
implicit none
real, intent(in) :: var2
real, intent(in) :: var3
real, …
```
> Global var hoisting

- loki/frontend/fparser.py
- loki/frontend/source.py
- loki/frontend/util.py
- loki/tools/util.py
- loki/visitors/transform.py
- tests/test_frontends.py
- tests/test_source.py
Several steps in the frontend utilities have sub-optimal performance scaling with the size of the IR tree being processed, thus inflating frontend parsing times for large files, as flagged in #227 . This PR aims to address this by replacing the expensive "search-and-replace" pattern with an on-the-fly processing of multi-line comments and pragmas.
Importantly, it also introduces a few small utilities to do multi-item sub-sequence finding and replacement in tuples, which makes this much neater and reduces the clutter a bit. One of those new utilities is now also used in the `Transformer` base class itself, and a small fix to `Source` lines was needed to make those hash correctly (we were still using lists! :scream:).
Final note: There probably more to be done for raw processing speed …
> Performance optimisations for frontend parsing/sanitising

- loki/backend/fgen.py
- loki/bulk/item.py
- loki/bulk/scheduler.py
- loki/transform/build_system_transform.py
- loki/transform/transform_hoist_variables.py
- loki/transform/transformation.py
- scripts/loki_transform.py
- tests/test_fgen.py
- tests/test_scheduler.py
- tests/test_transform_hoist_variables.py
- transformations/tests/test_pool_allocator.py
- transformations/transformations/pool_allocator.py
_Please note that this is a replay of some of the changes in Loki #135 , brought together with an alternative solution for determining stack-size across mulitple libs. A lot of the credit for this excellent work goes to @MichaelSt98 (sorry, in the rebase I dropped the commit authorship when separating the individual steps)._
The main purpose of the PR is to apply the remaining fixes to the `PoolAllocatorTransformation` in unison and enable it as the "scc-stack" mode in the `loki_transform.py convert`. With this, the PR enables the SCC-stack transformation for the current EC-physics demonstrator via three types of changes:
* Enabling the SCC-Stack transformation as a "mode" in convert (bug fix to deal with hyphens in "mode")
* Allowing the analysis part of SCC-stack to run past "ignore" …
> Enabling SCC-Stack for EC-physics, part 2

- loki/bulk/configure.py
- loki/bulk/item.py
- loki/bulk/scheduler.py
- loki/program_unit.py
- loki/sourcefile.py
- tests/test_scheduler.py
- transformations/tests/test_cloudsc.py
This adds the ability to overwrite frontend options on a per-file basis in the Scheduler config. This allows for example to switch on preprocessing for individual files only (e.g., for those that are not valid Fortran without preprocessing), or to overwrite the frontend parser. The latter was the missing piece to successfully run CLOUDSC regression with OMNI.
> Overwrite frontend options on a per-file basis in Scheduler config

- loki/frontend/fparser.py
- loki/tools/util.py
- tests/test_derived_types.py
- tests/test_fgen.py
- tests/test_subroutine.py
- tests/test_tools.py
_Note: This is the second part to optimising the performance of the FP frontend, as detailed in PR #234. It contributes significantly to the throughput number presented in #234 ._
The key idea behind this PR is to avoid the costly rescoping pass of the subroutine/module bodies after the initial IR generation. Instead we now use the `scope` argument passed through the AST-to-IR converter whenever possible.
One caveat to this is that we still need to do one `AttachScopes` pass after parsing the `spec`, as we might encounter symbols used in shape declarations out of sequence (yay, Fortran!). I have adjusted one of the tests to capture this accordingly.
There are also a few little tricks involved, and I've added a small utility to temporarily override dict values, as we now need to be careful …
> FParser: Perform in-place scope attachment during parse

- lint_rules/lint_rules/ifs_arpege_coding_standards.py
- lint_rules/lint_rules/ifs_coding_standards_2011.py
- lint_rules/tests/test_ifs_arpege_coding_standards.py
- loki/expression/mappers.py
- loki/expression/symbols.py
- loki/lint/reporter.py
- scripts/loki_lint.py
- tests/test_frontends.py
This adds an implementation of the first 3 (arbitrarily chosen) rules from the new coding standards as a new rules module and makes this the default rules module in loki-lint.py.
Piggy-backed is a small fix for the expression dimensions inference, which would fail with an exception when the dimension expression contains deferred type symbols. However, this exception is actually unnecessary and the deferred type symbol should just be used as-is.
The second fix is just in the output formatting for rule violations to a yaml file. So far, even without any violations it would have inserted an empty line for every file, and skips now over empty reports.
> Loki-lint: First 3 rules for new IFS-Arpégé coding standards

- loki/bulk/item.py
- loki/bulk/scheduler.py
- loki/transform/dependency_transform.py
- tests/sources/projA/module/kernelB_mod.F90
- tests/sources/projB/external/ext_driver_mod.f90
- tests/test_batch.py
- tests/test_scheduler.py
- tests/test_transform_dependency.py
- tests/test_transform_inline.py
- transformations/tests/test_data_offload.py
This adds the missing `ExternalItem` item type for the new Scheduler, that allows to parse incomplete source trees and adds missing dependencies as `ExternalItem`. 
The missing dependency's type (i.e., the Item type that we would have created if the respective source file was available) is stored as `origin_cls` on the `ExternalItem`.
`SFilter` has been amended to ignore externals or include those externals that would have matched the `item_filter`. That allows to identify missing items with the `strict` config option during processing.
> Add ExternalItem to allow building dependency graph with missing nodes

- loki/bulk/configure.py
- loki/bulk/scheduler.py
- loki/program_unit.py
- loki/sourcefile.py
- tests/test_cmake.py
- tests/test_lint/test_linter.py
- tests/test_scheduler.py
- transformations/tests/test_data_offload.py
- transformations/tests/test_pool_allocator.py
- transformations/tests/test_transform_derived_types.py
This PR brings in a set of small changes (mostly discussed offline) that aligns the new scheduler with prior behaviour and thus gets EC-physics to pass again (in a reasonable amount of time). The main updates are concerned with the CMake-planning stage, where we need to re-introduce the `enable_imports` option and honour it for default parse traversals, as well as the disabling of the SGraph caching (which otherwise makes things prohibitively slow).
In some more detail:
* Reduce the logging of `make_complete` to only trigger on non-REGEX frontends
* Avoid self-reference cycles when building the SGraph (no longer needed after `ExternalItem` addition, but thought I'd keep it anyways)
* (Temporarily) stop caching the SGraph, and instead re-build it after each use of discovery and …
> Updates for EC-physics regression

- loki/transform/dependency_transform.py
Small last-minute bug-fix for ec-phys that I found when I moved `disable` entries to `block` entries in the config.
> DependencyTransformation: Ensure tuples when adding "block" entries

- loki/ir.py
- tests/test_subroutine.py
Utilities for `CallStatement`s
* check whether `kwargs` are correctly ordered
* sort `kwargs`
* convert `kwargs` to args
necessary for e.g., F2C transpilation
> kwargs utilities

- loki/transform/transform_array_indexing.py
- tests/test_transform_array_indexing.py
allow to ignore specific dimensions ...
> Allow to ignore specific dimensions in "shift to zero indexing"

- transformations/tests/sources/projDerivedTypes/driver_mod.F90
- transformations/tests/sources/projDerivedTypes/kernel_mod.F90
- transformations/tests/sources/projDerivedTypes/some_derived_type.F90
- transformations/tests/test_transform_derived_types.py
- transformations/transformations/derived_types.py
... with a proper test using the scheduler
> Add 'reverse_traversal=True' to DerivedTypeArgumentsTransformation manifest

- loki/tools/files.py
- tests/test_tools.py
This expands the `gettempdir` utility to
1. create pid-specific temporary directory to avoid race conditions among concurrent Loki executions (hoping this resolves the CI failures with OMNI regression testing)
2. clean up the temporary directory when the python interpreter terminates
> Create a pid-specific temporary directory and clean it up at the end

- transformations/tests/sources/projGlobalVarImports/functions.F90
- transformations/tests/sources/projGlobalVarImports/kernels.F90
- transformations/tests/test_data_offload.py
- transformations/transformations/data_offload.py
This adds proper handling of functions/inline calls for the `GlobalVarHoistTransformation` transformation. 
Problem was related to *arguments*/*parameters* missing in the inline call signature ...
> `GlobalVarHoistTransformation`: fix for functions/inline calls

- loki/transform/transform_array_indexing.py
- tests/test_transform_array_indexing.py
allow arrays with all dimensions being ':' e.g., `some_array(:, :, :)`
> Support colon notation for all dimensions in flatten_arrays

- cmake/loki_transform.cmake
This PR makes small additions to the cmake functions. This is the first of three required to run loki transformations on the SL.
> Small CMake layer fixes for SL

- transformations/tests/test_single_column_coalesced.py
- transformations/transformations/single_column_coalesced_vector.py
Pretty much what it says on the tin: somehow we've missed demoting arrays that are unused in the body but are otherwise perfectly fine to demote in the SCC-family demotion step. This PR fixes this.
> SingleColumn: Demote arrays that are not used at all in the body

- loki/batch/item.py
- loki/frontend/regex.py
- tests/test_batch.py
- tests/test_frontends.py
Procedures in missing modules (that are recognized as ExternalItem) were not recognized as ExternalItems and instead created as ProcedureItem with missing source. This fixes that erroneous behaviour.
> Scheduler: Fix handling of external module procedures

- loki/transform/dependency_transform.py
- tests/test_transform_dependency.py
An imported statement function (😭 ) with the same root as a target subroutine is overwritten by the dependency transformation. This PR fixes the above.
> Preserve imported statement functions

- loki/expression/expr_visitors.py
- loki/transform/transform_utilities.py
- tests/test_subroutine.py
- tests/test_transform_utilities.py
`replace_intrinsics()` wasn't working properly, especially for used symbols/functions within the `routine.spec` e.g., for initialising parameters ...
`rename_variables()` as additional utility to rename variables/arguments e.g. `const` within ecwam ...
> improved `replace_intrinsics` and added `rename_variables`

- loki/backend/cgen.py
- loki/backend/fgen.py
- loki/subroutine.py
- loki/transform/dependency_transform.py
- loki/transform/fortran_c_transform.py
- tests/test_subroutine.py
- tests/test_transform_dependency.py
- tests/test_transpile.py
`cgen`: return type and var for function(s)
> `cgen`: return type and var for function(s)

- loki/batch/configure.py
- loki/dimension.py
- loki/transform/pipeline.py
- loki/transform/transformation.py
- scripts/loki_transform.py
- tests/test_scheduler.py
- tests/test_transformation.py
_Note this PR is built on top of and depends on #260._
This PR extends the `Pipeline` abstraction to make it composable and allow configuration from via the scheduler config files (in .yml). In particular, it adds `prepend`/`append` methods and support for a native `pipeline += trafo` notation to allow building custom pipelines from instantiated pipelines and transformations. 
It then also adds a new entry to the scheduler config where custom, complex transformation pipelines can be defined that combine internally provided, as well as externally defined transformations to allow full customisation outside of the usual top-level entry points. The use of custom transformation pipelines is then exposed via `loki-transform.py convert`.
This new generic interface for custom pipelines allows us …
> Pipeline configuration from file

- loki/expression/expr_visitors.py
- loki/scope.py
- loki/transform/transform_inline.py
- tests/test_transform_inline.py
A curious corner case when inlining procedures that would result in nested associates, as the newly created parentage cannot be inferred via the usual pin-hole insertion approach. So, instead we now ensure that we update the parent in `AttachScopes` and call this after the call-inlining is finalised. A test is provided that illustrates the problem.
> Fixing nested associate scope-parentage tracking after inlining

- loki/backend/cgen.py
- loki/transform/fortran_c_transform.py
- tests/test_transpile.py
`DeReferenceTrafo` for and within `FortranCTransformation` to insert apply/insert `Dereference` = `*` and `Reference`/*address-of* = `&` operators.
> F2C: `DeReferenceTrafo`

- loki/frontend/regex.py
- tests/test_frontends.py
Discovered with IFS source files.
Two small fixes for the REGEX frontend patterns, with tests that triggered before the corresponding changes:
- Multiple or no white space around the `end` statement for procedures
- Matching of module procedures is now lazy to match internal subprograms in module procedures
> REGEX frontend: white space and nesting bugfix

- transformations/tests/test_data_offload.py
- transformations/transformations/data_offload.py
Global variables imported at the driver layer passed down to the compute kernel as a subroutine argument should not be included in the `GlobalVariableAnalysis`. Rather, they should be handled via the `DataOffloadTransformation`.
> Skip driver routine in `GlobalVariableAnalysis`

- loki/ir/transformer.py
- tests/test_visitor.py
The offending line was accidentally packing the `associations` tuple and `body` tuple of `Associate` object together on rebuild, which inserted rogue symbols into the body of the associate when it is rebuilt in-place. This happens, for example, during pragma-region attachment.
> MaskedTransformer: Fix in-place rebuilding of scoped nodes

- loki/expression/symbols.py
- tests/test_expression.py
I played around a little with this because I wanted to see if we can get away without using the symbol's `variable_map`, which can be costly for large and nested derived types. For this, I've also added an additional test that validates that type information is derived correctly.
> Avoid variable_map in TypedSymbol.get_derived_type_member and verify type information is derived correctly

- loki/transform/transform_hoist_variables.py
- tests/sources/projHoist/module/driver_inline_mod.f90
- tests/sources/projHoist/module/subroutines_inline_mod.f90
- tests/test_transform_hoist_variables.py
This PR adds the capability to hoist temporaries declared in inline function calls. It also changes the default behaviour so that statically declared arrays are no longer hoisted.
> SCCHoist: hoist inline call temporaries and don't hoist statically declared arrays

- transformations/tests/test_single_column_coalesced.py
- transformations/transformations/single_column_base.py
The `get_integer_variable` utility in `SCCBaseTransformation` now also checks if the integer has been imported via a module.
> `SCCBaseTransformation.get_integer_variable` now also checks module imports

- loki/pragma_utils.py
A subtle but significant performance bug meant that attaching/detaching pragma-regions was becoming ver expensive for large code regions, eg. when finding marked regions to remove (PR #276). This PR fixes this by re-implementing the matching and resolution of `PragmaRegion` objects with custom in-place transformers that perform the matching at tuple-level.
One important consideration here is that we now only match pragma-pairs at tuple level, and thus have an implicit check for misplaced `!$loki end <marker>` pragmas, that will now trigger warnings. We also need to be very careful about tuple-insertion when resolving the regions objects during detach, as we do not want nested tuples in our IR tree, but cannot use `flatten` on tuples generically. This is marked via comments in the …
> Improve performance of pragma-region attach/detach by using transformers

- loki/frontend/util.py
This is a hotfix following merge of #287
> [Bugfix] available_frontends: Import pytest locally to make dependency optional

- loki/analyse/analyse_dataflow.py
- loki/analyse/tests/test_analyse_dataflow.py
The `_visit_body` method in the `DataflowAnalysis` flattens the bodies, which can sometimes lead to invalid IR. This PR provides a fix.
> `DataflowAnalysis` bugfix: preserve body nesting in `visit_MaskedStatement`

- loki/analyse/tests/test_util_polyhedron.py
- loki/expression/__init__.py
- loki/expression/parser.py
- loki/expression/tests/test_expression.py
- loki/expression/tests/test_symbolic.py
- loki/frontend/fparser.py
- loki/transform/transform_loop.py
@mlange05 and @reuterbal : could you please have a look so we can have a discussion about whether this is the best approach to parse expressions from strings? 
As `parse_fparser_expression` is not always usable/sufficient, this is a demonstrator for a possible parser based on pymbolic's parser. For example `process_dimension_pragmas` is used within `fparser` and thus can't utilise `parse_fparser_expression`. With trivial dimension pragmas and/or if those dimensions read from the pragmas are not further transformed, this is not a problem. However, for more complex dimension pragmas like `!$loki dimension(A,0:B/2,C,D)` this becomes a problem ...
```py
>>> from loki.expression.parser import loki_parse
>>> expr = loki_parse('((a + b)/(a - b))**3 + 3.1415')
>>> expr …
```
> Loki expression parser based on pymbolic parser

- loki/backend/cgen.py
- loki/expression/symbols.py
- loki/tests/test_transpile.py
- loki/transform/fortran_c_transform.py
- loki/transform/transform_utilities.py
`convert_to_lower_case()` if not variable/symbol `.case_sensitive=True`
Imported for things like: 
```c
... = threadIdx.x
cudaMalloc(...)
```
> F2C: optional case-sensitivity for variables/symbols

- transformations/tests/test_scc_cuf.py
- transformations/transformations/scc_cuf.py
hoisting arrays via pragma offload for low-level GPU implementations (no block index, which makes it different to `SCCHoistTemporaryArraysTransformation`)
> Transformation to hoist temporaries in kernel language transpilation

- transformations/tests/test_data_offload.py
- transformations/transformations/data_offload.py
fix scoping for `GlobalVarHoistTransformation'`
> fix scoping for global var hoisting

- loki/dimension.py
- loki/expression/tests/test_expression.py
- loki/program_unit.py
- loki/tests/test_dimension.py
- loki/tools/util.py
- transformations/tests/test_single_column_coalesced.py
- transformations/transformations/pool_allocator.py
- transformations/transformations/single_column_base.py
- transformations/transformations/single_column_coalesced_vector.py
This is the final PR needed to transform the SL. It consists of a series of fixes to the SCC transforms, the biggest of which is the ability to use aliased components of a derived-type as the horizontal loop bounds.
NB: this is stacked on top of #249.
> SCC: Support for bounds aliases and derived type members as bounds

- loki/build/compiler.py
- loki/build/jit.py
- loki/build/tests/test_build.py
JIT compilation was hard coded to `gfortran` and not using the `Compiler` class in the `compile_and_load` method used throughout the test base. This prevented testing with other gfortran versions or different compilers.
The first change in this PR is to make Loki use consistently the `Compiler` class for JIT compilation. This unlocks the use of other compilers when executing tests.
The second change is to inspect the environment for common variables setting the compiler (`CC`, `FC`, `F90`) and choose an appropriate compiler. This consists of two steps:
1. First, we try to identify the compiler "family", for which now "GNU" and "Nvidia" exist (I used the opportuinity to delete the ancient "ESCAPE" compiler definition). This is done by matching the value in the respective env variable …
> Consistent, environment-configurable use of Compiler class in JIT compilation

- loki/ir/nodes.py
- loki/tests/test_derived_types.py
This PR adds the ability to propagate all the non-overridden symbols from a parent to a child type. It should be noted that per the Fortran standard, only type-bound procedures can be shadowed by children and data/procedure members cannot, but I have kept the implementation agnostic to the type of symbol being inherited.
> Derived-type inheritance

- loki/expression/expr_visitors.py
- loki/expression/parser.py
- loki/expression/tests/test_expression.py
- loki/frontend/fparser.py
- loki/frontend/ofp.py
- loki/frontend/omni.py
- loki/frontend/tests/test_frontends.py
- loki/ir/pragma_utils.py
- loki/ir/tests/test_pragma_utils.py
- loki/tests/test_subroutine.py
Improve `parse_expr` and use in `process_dimension_pragmas`.
* add correct parsing of `:` to `RangeIndex((None, None))`
* support `DerivedType` s
> Improve `parse_expr` and use in `process_dimension_pragmas`

- .github/workflows/code_checks.yml
- .github/workflows/documentation.yml
- .github/workflows/regression_tests.yml
- .github/workflows/tests.yml
Small bugfix PR: The GH workflows did not fetch tags in the clone, therefore the Loki version number was always wrong (including in the published docs).
> Fetch tags in Github workflows

- loki/frontend/fparser.py
- loki/frontend/ofp.py
- loki/frontend/omni.py
- loki/frontend/tests/test_frontends.py
As described in #309, imports of private symbols destroys the type inference. This pull request propose a simple check of symbols access specificators to filter out the private symbols.
TODO:
> Fix: import of private symbols affects the type inference

- loki/batch/tests/test_batch.py
- loki/batch/tests/test_scheduler.py
- loki/batch/tests/test_transformation.py
- loki/build/obj.py
- loki/build/tests/test_build.py
- loki/expression/tests/test_expression.py
- loki/frontend/tests/test_frontends.py
- loki/lint/tests/test_linter.py
- loki/lint/tests/test_reporter.py
- loki/tests/sources/sourcefile_cpp_stmt_func.F90
- loki/tests/test_derived_types.py
- loki/tests/test_sourcefile.py
- loki/transformations/build_system/tests/test_dependency.py
- loki/transformations/single_column/tests/test_single_column_coalesced.py
- loki/transformations/tests/test_array_indexing.py
- loki/transformations/tests/test_data_offload.py
- loki/transformations/tests/test_hoist_variables.py
- loki/transformations/tests/test_inline.py
- loki/transformations/tests/test_parametrise.py
- loki/transformations/tests/test_pool_allocator.py
- loki/transformations/tests/test_transform_derived_types.py
- loki/transformations/tests/test_transform_region.py
- loki/transformations/transpile/tests/test_maxeler/test_maxeler.py
- loki/transformations/transpile/tests/test_sdfg.py
- loki/transformations/transpile/tests/test_transpile.py
The latest release of f90wrap includes module names in the name of generated interface routines (introduced in https://github.com/jameskermode/f90wrap/pull/215). This lets them grow quickly beyond the Fortran length limit of 63 characters for names, and gfortran (not even 13.2) does not allow to lift that limitation.
Therefore, I have shorted the module and routine names in the test base where the character limit was exceeded.
In the process, I also introduced the use of `tempdir` fixtures more widely to ensure clean-up of test files is handled gracefully and the littering of the source directory is reduced.
> JIT compilation updates and compatibility with f90wrap v0.2.14

- loki/ir/pragma_utils.py
- loki/ir/tests/test_pragma_utils.py
- scripts/loki_transform.py
The recent addition of `parse_expr` for reading pragma parameters does not account for multi-line pragmas with `&` linebreaks. This PR fixes this and adds a small test for this.
I've also piggy-backed a small fix to loki-transform.py, where the recent introduction of `RemoveCodeTransformation` was not told to keep `DR_HOOK` calls in the drivers via the `kernel_only` option. With these two changes, EC-physics regression should be fine again.
> IR: Fix `get_pragma_params` for multiline pragmas

- loki/frontend/regex.py
- loki/frontend/tests/test_regex_frontend.py
This fixes #318. Thanks @piotrows for reporting this and providing a small reproducer.
> Fix parse failures with REGEX frontend due to white space in declarations

- loki/ir/nodes.py
- loki/tests/test_derived_types.py
This assumed parent definition was always available in the symbol table, which it isn't if the parent is defined in a different module and no enrichment has been applied.
> Fix derived type inheritance when parent type is not available (#330)

- loki/batch/scheduler.py
- loki/batch/transformation.py
- loki/transformations/inline.py
- loki/transformations/tests/test_inline.py
Certain transformations (e.g. `InlineTransformation`) might create or delete callgraph edges without renaming or creating new items. Updating the `sgraph` in such cases requires only `scheduler._discover` to be triggered. This PR adds such an option to the `Transformation` class.
> InlineTransformation: Update Scheduler SGraph if marked_inline is activated

- loki/transformations/hoist_variables.py
- loki/transformations/inline.py
- loki/transformations/single_column/hoist.py
- loki/transformations/single_column/tests/test_single_column_coalesced.py
- loki/transformations/tests/test_inline.py
This small PR implements two bug fixes:
- `HoistVariablesAnalysis` now skips successors that might no longer be present (e.g. they were inlined)
- Unused explicit interfaces of inlined subroutines are now removed
> `HoistVariablesAnalysis`: remove unused explicit interfaces after inlining

- lint_rules/lint_rules/ifs_arpege_coding_standards.py
- lint_rules/tests/test_ifs_arpege_coding_standards.py
Another beautiful edge case but this time purely in Linter recipes: 
- apparently, interface blocks may not only be declared in `.intfb.h` headers, but also in `.func.h` headers
- inline calls with string parameters can actually be identified as inline calls (rather than array subscripts) by fparser
> Fix Linter warnings for inline calls with interface block imported from header with func.h suffix

- loki/transformations/hoist_variables.py
- loki/transformations/inline.py
- loki/transformations/pool_allocator.py
- loki/transformations/tests/test_hoist_variables.py
- loki/transformations/tests/test_inline.py
- loki/transformations/tests/test_pool_allocator.py
This PR provides the following fixes:
1. `TemporariesPoolAllocator` transformation now adds global variable imports to the driver for variables used to define array sizes.
2. `HoistArraysTransformation` adds imports used to define the sizes of hoisted variables.
3.  The addition of module imports from inlined children in the `InlineTransformation` is fixed.
4. `InlineTransformation` now also adds any explicit interfaces from inlined children.
> Add transformation generated imports to driver or after inlining

- loki/ir/pragma_utils.py
- loki/ir/tests/test_pragma_utils.py
This fixes the issue reported in #317
> get_pragma_parameters: Fix parsing clauses without parentheses in the tail string

- loki/expression/symbols.py
- loki/frontend/fparser.py
- loki/frontend/ofp.py
- loki/frontend/omni.py
- loki/program_unit.py
- loki/tests/test_modules.py
- loki/tests/test_subroutine.py
- loki/transformations/single_column/base.py
- loki/transformations/tests/test_scc_cuf.py
This fixes #307.
Piggy-backed is a small fix with test for missing enrichment between modules within the same source file, reported in #161.
> ProgramUnit.resolve_typebound_var: raise error if top-level parent is not declared

- loki/transformations/drhook.py
- loki/transformations/tests/test_drhook.py
- scripts/loki_transform.py
This PR adds an renaming option to the `DrHookTransformation` that allows and explicit renaming via a string-to-string dict in addition to the current append-suffix mode. This allows a broader use for this housekeeping transformation, eg. when generating control-flow subroutines.
With this, I've also added a few minor clean-ups and fixes, as detailed below:
* Rename the argument `mode` to `suffix`, as it's a suffix we add to the DR_HOOK labels
* Use the `Transformation.recurse_to_internal_procedures` class property instead of explicit recursion calls
* Add a `kernel_only` argument (`True` by default), with which we can force it to apply to "driver" routines as well
* Add `rename` argument (dict) that gets used when/if a label is matched for explicit label renaming.
> DrHookTransformation: Add explicit label renaming

- loki/frontend/fparser.py
- loki/frontend/ofp.py
- loki/ir/tests/test_control_flow.py
The Cray pointer statement is understood by OFP and FParser but was not handled when translating the parse tree to Loki's IR. This adds functionality to represent these as `Intrinsic` nodes in the IR.
> Support for representing cray pointers using OFP or FP (fixes #338)

- loki/transformations/inline.py
- loki/transformations/tests/test_inline.py
- loki/transformations/utilities.py
* OFP excluded from test because of some problems with Statement Functions I haven't investigated further yet
* if the order or statement function declaration is "wrong" this won't work as the statement function would be interpreted as array access ... but this is a problem that has nothing to do with the inlining itself
From
```fortran
subroutine stmt_func(arr, ret)
implicit none
real, intent(in) :: arr(:)
real, intent(inout) :: ret(:)
real :: ret2
real, parameter :: rtt = 1.0
real :: PTARE
real :: FOEDELTA
FOEDELTA ( PTARE ) = PTARE + 1.0
real :: FOEEW
FOEEW ( PTARE ) = PTARE + FOEDELTA(PTARE)
ret = foeew(arr) 
ret2 = foedelta(3.0)
end subroutine stmt_func
```
to
```fortran
SUBROUTINE stmt_func (arr, ret)
IMPLICIT NONE
REAL, INTENT(IN) :: arr(:)
REAL, INTENT(INOUT) :: ret(:)
REAL :: …
```
> Allow inlining of Statement Functions

- loki/backend/tests/test_cufgen.py
- loki/frontend/fparser.py
- loki/ir/nodes.py
- loki/ir/tests/test_ir_nodes.py
- pyproject.toml
~_Note:` For now, just for testing..._~
This PR brings a few enabling changes to the internal IR node definitions that allow us to lift the version restriction on `pydantic`. We needed this previously, as we were relying on some (broken) default behaviour that was fixed upstream in pydantic version 2. By changing to the correct type annotations, in particular for `Optional` arguments, we can now lift this restriction.
In addition, I also added a small set of rudimentary checks for the constructor and object behaviour (immutability) for three most common/interesting node types. I plan to expand on this somewhat in a follow-up PR that will require pydantic features from version 2.x. 
In some more detail:
* Use `Optional` throughout node type annotations to allow default values of `None`
* …
> IR: Update to Pydantic >2.0 compatibility

- .github/workflows/regression_tests.yml
- loki/transformations/tests/test_ecwam.py
A few small changes to fix the ecwam regression tests. What was causing the runtime failures was the default `DEV_ALLOC_SIZE` in the FIELD_API buddy allocator. The change to the fypp+pyyaml installation is for a future ecwam update which relies on (in the absence of fckit) the system python installation having fypp+pyyaml.
> Fix DEV_ALLOC_SIZE for ecwam regression and add SCC-HOIST variant

- AUTHORS.md
- loki/transformations/tests/test_transform_loop.py
- loki/transformations/transform_loop.py
This PR introduces a new transform, and associated pragma (`!$loki loop-unroll [depth(n)]`), for unrolling loops. It supports nesting & the ability to only unroll nested loops to a certain depth.
> Add loop unroll transformation

- .github/workflows/tests.yml
- CMakeLists.txt
- INSTALL.md
- cmake/python_venv.cmake
- install
- loki-post-import.cmake.in
- loki/batch/tests/test_batch.py
- loki/tests/test_cmake.py
- loki/tests/test_modules.py
- loki/tools/tests/test_tools.py
- loki/transformations/tests/test_array_indexing.py
With people using Loki locally on their MacBooks, it seems useful to test this as part of the CI.
> Run pytest on macos in GH actions

- loki/transformations/block_index_transformations.py
- loki/transformations/single_column/annotate.py
- loki/transformations/single_column/base.py
- loki/transformations/single_column/hoist.py
- loki/transformations/single_column/scc_cuf.py
- loki/transformations/single_column/tests/test_scc.py
- loki/transformations/single_column/vector.py
- loki/transformations/tests/test_utilities.py
- loki/transformations/utilities.py
~Another small housekeeping change. This one adds a new sub-package `transformations.single_column.util` sub-package for common utilities that may be used across the several SCC sub-stages.~
A small housekeeping change that moves utility methods from `SCCBaseTransformation` to the the common `transformations.utilities` subpackage. This primarily removes the awkward dependency on the `SCCBaseTransformation` class in other SCC sub-components, which provided this previously. 
This change is largely cosmetic (simply copying methods over), except for the `get_local_arrays` utility, which is now used by the demotion and the annotations sub-component. This is in preparation for a more complex refactoring of the annotation sub-component to support multiple vectorisation and annotation schemes in …
> Transformations: Move common SCC utility routines to `utilities`

- loki/transformations/tests/test_utilities.py
- loki/transformations/utilities.py
_Note: This is a small bug fix to #354 that was overlooked and is currently breaking H24-physics regression._
When running get_local_arrays over the spec of a subroutine we were erroneously picking up component arrays of derived-type arguments that were used for shape definitions. This extends the test for this corner case and fixes it.
> Transformations: Test and fix corner case in get_local_arrays

- loki/tools/tests/test_tools.py
We suspect the failures to be due to load on CI runners, so disabling this test for now.
> Tools: Disable timeout utility test on MacOS due to sporadic failures

- .github/workflows/regression_tests.yml
Technical development in ecWAM will (at least for the short term) lag one cycle behind the latest scientific version. Therefore it makes more sense to run the loki regression tests on `develop-1.3` which will be the staging branch for further technical developments on top of 49r1 science.
> ecWAM regression tests: switch to develop-1.3 branch

- loki/transformations/__init__.py
- loki/transformations/split_read_write.py
- loki/transformations/tests/test_split_read_write.py
- scripts/loki_transform.py
Lukas M. demonstrated that for accumulation patterns of the type:
```
do jlon=1,nproma
var(jlon, n1) = var(jlon, n1) + 1.
var(jlon, n2) = var(jlon, n2) + 1.
enddo
```
a compiler cannot rule out the possibility that `n1` and `n2` do not in fact alias the same location. In such a case, it is unable to run the loads and stores out-of-order.
This PR contributes a pragma assisted transformation to split the above into separate reads and writes, thereby removing the dependency between subsequent loads and stores and allowing the compiler to optimise more effectively.
> Split reads and writes for certain accumulation patterns

- loki/transformations/array_indexing.py
- loki/transformations/tests/test_array_indexing.py
problem occurred whenever two dimensions had the same size
e.g.,
```fortran
integer :: ret1(param1, param1)
...
ret1(:, :) = 0
```
resulted in:
```fortran
DO i_ret1_1=1,param1
DO i_ret1_0=1,param1
ret1(i_ret1_1, i_ret1_1) = 0
END DO
END DO
```
instead of the correct result:
```fortran
DO i_ret1_1=1,param1
DO i_ret1_0=1,param1
ret1(i_ret1_0, i_ret1_1) = 0
END DO
END DO
```
> fix for 'resolve_vector_notation' utility

- loki/batch/configure.py
- loki/batch/tests/test_scheduler.py
- loki/frontend/tests/test_frontends.py
- loki/transformations/__init__.py
- loki/transformations/idempotence.py
- loki/transformations/tests/test_idempotence.py
- scripts/loki_transform.py
This change move the `IdemTransformation` that we often use for testing to the `loki.transformations` sub-package and fixes a configure bug when omitting the `options` entry in TOML(!)-based configuration entries. This is in preparation for the full move to config-file transformation configuration in CLOUDSC.
> Transformations: Internalise `IdemTransformation`

- loki/expression/tests/test_expression.py
- loki/frontend/tests/test_frontends.py
- loki/frontend/tests/test_omni.py
- loki/frontend/util.py
- loki/tests/test_derived_types.py
- loki/tests/test_modules.py
- loki/tests/test_subroutine.py
- loki/transformations/single_column/tests/test_scc.py
- loki/transformations/tests/test_array_indexing.py
- loki/transformations/tests/test_data_offload.py
- loki/transformations/tests/test_extract.py
- loki/transformations/tests/test_hoist_variables.py
- loki/transformations/tests/test_inline.py
- loki/transformations/tests/test_parametrise.py
- loki/transformations/tests/test_pool_allocator.py
- loki/transformations/tests/test_raw_stack_allocator.py
- loki/transformations/tests/test_transform_derived_types.py
- loki/transformations/tests/test_transform_loop.py
- loki/transformations/tests/test_transform_region.py
- loki/transformations/tests/test_utilities.py
- loki/transformations/transpile/fortran_maxeler.py
- loki/transformations/transpile/fortran_python.py
- loki/transformations/transpile/tests/test_transpile.py
- scripts/loki_transform.py
~Just testing for now ...~
This change adds a frontend sanitisation step to remove the forced lower bounds on array declaration dimensions in OMNI. This is done via a custom sanitisation `Transformer`. 
As a result, we can remove a lot of the special-casing for OMNI's array dimension notation and, importantly, remove the use of the `normalize_range_indexing` utility across the `loki.transformation` sub-package tests. Consequently, we can also remove the OMNI special-casing in `loki_transform.py` - the problem that triggered this entire endeavour.
Please note, the `normalize_range_indexing` tool has not been removed, as it has a legitimate use in another sanitisation utility, which is part of the C-transpilation toolchain. However, all OMNI-specific workarounds using this utility have been …
> OMNI: Fix dimension range-indexing in frontend

- scripts/loki_transform.py
This is a small workaround for enabling SCC-CUF pipelines from config file in CLOUDSC. As we still push static config info alongside dynamic build system settings, this is needed for now if we don't want to preprocess the loki config via cmake.
> Loki-transform: Pass `cuf` option to FilewriteTrafo

- loki/transformations/tests/test_utilities.py
- loki/transformations/utilities.py
A small PR to filter out global variables from `get_local_arrays`; these may be included if `get_local_arrays` is applied to `routine.spec`.
> Filter out globals in `get_local_arrays`

- loki/transformations/hoist_variables.py
- loki/transformations/tests/test_hoist_variables.py
to account for possibly uninitialised variables used as dimensions (if wanted via flag)
This 
```fortran
subroutine driver(NLON, NB, FIELD1)
use kernel_mod, only: kernel
implicit none
INTEGER, INTENT(IN) :: NLON, NB
integer :: b
integer, intent(inout) :: field1(nlon, nb)
integer :: local_nlon
local_nlon = nlon
do b=1,nb
call KERNEL(local_nlon, field1(:,b))
end do
end subroutine driver
```
would be transformed to
```fortran
SUBROUTINE driver (NLON, NB, field1)
USE kernel_mod, ONLY: kernel
implicit none
INTEGER, INTENT(IN) :: NLON, NB
INTEGER :: b
INTEGER, INTENT(INOUT) :: field1(nlon, nb)
INTEGER :: local_nlon
INTEGER :: kernel_tmp1(local_nlon)
local_nlon = nlon
DO b=1,nb
CALL KERNEL(local_nlon, field1(:, b), kernel_tmp1)
END DO
END SUBROUTINE driver
```
which would be a problem as …
> extend hoist variables functionality

- scripts/loki_transform.py
Not sure whether I am missing something, but shouldn't the `SCCRawStackPipeline` be called for mode `scc-raw-stack`?
> Change/fix pipeline for mode 'scc-raw-stack'

- loki/transformations/pool_allocator.py
- loki/transformations/tests/test_pool_allocator.py
- scripts/loki_transform.py
Currently, the pool allocator pads every allocation to 8 bytes to avoid potential memory alignment issues on device. This is only strictly necessary for arrays that are not `NPROMA` sized, as this is likely to be a multiple of 8 in any case. If only such arrays are padded, then the memory footprint of the stack can potentially be reduced, especially for single precision builds.
Once this PR is reviewed, accepted and merged, could it please be tagged?
> Minimal padding in pool allocator

- loki/backend/__init__.py
- loki/backend/cgen.py
- loki/backend/cppgen.py
- loki/backend/cudagen.py
- loki/tools/util.py
- loki/transformations/array_indexing.py
- loki/transformations/block_index_transformations.py
- loki/transformations/data_offload.py
- loki/transformations/single_column/__init__.py
- loki/transformations/single_column/base.py
- loki/transformations/single_column/scc_cuf.py
- loki/transformations/single_column/scc_low_level.py
- loki/transformations/single_column/vector.py
- loki/transformations/tests/sources/projSccCuf/module/driver.f90
- loki/transformations/tests/sources/projSccCuf/module/kernel.f90
- loki/transformations/tests/test_array_indexing.py
- loki/transformations/tests/test_block_index_inject.py
- loki/transformations/tests/test_scc_cuf.py
- loki/transformations/transpile/fortran_c.py
- loki/transformations/transpile/tests/test_transpile.py
- scripts/loki_transform.py
Still work in progress ... 
Corresponding CLOUDSC branch `nams-cloudsc-low-level-GPU`
Build via `cloudsc-bundle build --clean --arch=arch/ecmwf/hpc2020/nvhpc/22.11 --with-loki --with-gpu --with-cuda`
New modes/binaries: 
* `./bin/dwarf-cloudsc-loki-idem-lower` CPU variant with lowered block index
* `./bin/dwarf-cloudsc-loki-idem-lower-loop` CPU variant with lowered block index and loop
* `./bin/dwarf-cloudsc-loki-scc-parametrise-cuda` SCC-PARAMETRISE CUDA C
* `./bin/dwarf-cloudsc-loki-scc-hoist-cuda` SCC-HOIST CUDA C
Furthermore, usage of pipelines:
```
SCCLowLevelCufParametrise = partial(
Pipeline, classes=(
SCCBaseTransformation,
SCCDevectorTransformation,
SCCDemoteTransformation,
SCCRevectorTransformation,
LowerBlockIndexTransformation,
InjectBlockIndexTransformation, …
```
> CLOUDSC low-level GPU (transpilation) via Loki (CUF/CUDA)

- loki/transformations/block_index_transformations.py
- loki/transformations/single_column/annotate.py
- loki/transformations/single_column/base.py
- loki/transformations/single_column/tests/test_scc.py
- loki/transformations/single_column/tests/test_scc_hoist.py
- loki/transformations/single_column/tests/test_scc_vector.py
- loki/transformations/single_column/vector.py
- loki/transformations/tests/test_utilities.py
- loki/transformations/utilities.py
~_Note: Just testing for now..._~
This PR changes the way we add OpenACC annotations in the SCC pipelines and generally refactors `SCCAnnotate` and `SCCRevector`. The key change is that we now insert Loki-specific annotations for vector-loops, driver loops, routine annotations and vector reductions in `SCCRevector` and then let `SCCAnnotate` translate this into OpenACC directives. This is in preparation for the addition of an additional re-vectorisation scheme and the eventual support for OpenMP-offload in the SCC pipelines, as it will allow `SCCAnnotate` to easily switch between directive flavours.
There's also quite a bit of refactoring and clean-up, in particular in the upper control methods of `SCCAnnotate`, as well as the utility method `check_routine_pragmas`. Overall I hope this is …
> SCC: Add vectorisation annotations in SCCRevector and translate in SCCAnnotate 

- loki/backend/cgen.py
- loki/transformations/transpile/tests/test_transpile.py
Improve on multiconditionals/switch/select case for c-like-backends ...
this includes handling of RangeIndex as case value
> Improve on multiconditionals/switch/select case

- loki/backend/cgen.py
- loki/backend/cppgen.py
- loki/build/compiler.py
- loki/build/obj.py
- loki/transformations/transpile/fortran_c.py
- loki/transformations/transpile/tests/test_transpile.py
Allow/handle optional arguments for c-like-backends.
For 
* `cgen` - assume all optional arguments are passed (inherently unsafe, thus warn)
* `cppgen` (and all backends derived from that) - proper handling via optional argument with default value `nullptr`
* arguments that would have been passed by value are instead passed as pointer if they are optional
Moreover, introduced capabilities to jit compile C++ files (in addition to C files).
> Transpilation: optional arguments

- loki/transformations/single_column/tests/test_scc_vector.py
- loki/transformations/single_column/vector.py
conflicting with (rebuild of) Conditional.
Fixes #380
> Fix edge case for vector section mapping

- loki/ir/nodes.py
- loki/ir/tests/test_scoped_nodes.py
- loki/program_unit.py
~_Note: This PR sits on top of #372, so I'm only filing a draft before anticipated rebase._~
This PR brings a set of convenience methods and expression constructors to the `ScopedNode` and `ProgramUnit` classes. The idea is that eventually, `Subroutine` and `Module` classes should become scoped nodes and the expression management API should be equivalent between them.
The idea is to add the following three utilities to the scope objects themselves, to enable quick(er) expression generation:
* `.get_symbol(name)` - utility to look up a symbol by it's name. This will first find it's true owning scope and attach the symbol.
* `.Variable(name, ....)` - a shortcut to the general `Variable` constructor that will attempt to build array and scalar symbols, depending on available type information …
> IR: Symbol management on scoped nodes

- loki/transformations/array_indexing.py
- loki/transformations/tests/test_array_indexing.py
Imagine having:
```fortran
integer :: arr1(n), arr2(n)
arr1(:) = 0
do j=1,n
arr2(j) = 0
enddo
```
Instead of transforming this to:
```fortran
integer :: arr1(n), arr2(n)
do i_arr1_0=1,n
arr1(j) = 0
enddo
do j=1,n
arr2(j) = 0
enddo
```
transform it to:
```fortran
integer :: arr1(n), arr2(n)
do j=1,n
arr1(j) = 0
enddo
do j=1,n
arr2(j) = 0
enddo
```
If there is no loop with appropriate bounds introduce new loop variable (like it was before in general).
> Extend 'resolve_vector_notation' to look for available and appropriate loops

- loki/frontend/omni.py
- loki/tests/test_subroutine.py
The translation of the OMNI AST into the Loki IR dropped the shape information of the return type, representing the return value always as scalar. This PR fixes the behaviour and adds a test.
Small caveat is that with OMNI the dimension information will always be put on the variable, i.e., both
* `real, dimension(n) :: ret_val`
* `real :: ret_val(n)`
will always be represented as the latter. But since string-identical parse-unparse cycle is not achievable with OMNI anyway, I consider this not too important. Please shout if you disagree.
This PR should fix the problems that @MichaelSt98 encountered with OMNI in #378.
> Fix representation of array return type in OMNI frontend

- loki/ir/nodes.py
- loki/ir/tests/test_ir_nodes.py
- loki/transformations/single_column/tests/test_scc_vector.py
- loki/transformations/single_column/vector.py
The recent special-casing for else-if branches in the SCC vectorisation only works for single-level nesting, but skips any further nested else-ifs and the final else-branch. TO fix this, i've introduced a `else_bodies` property on `Conditional` nodes that returns the nested bodies for multi-conditionals. Using this, this we can then apply vector-section extraction for every else body in a deeply nested multi-conditional.
> SingleColumn: Fix vectorisation of nested else-if bodies

- loki/expression/symbols.py
- loki/transformations/inline.py
- loki/transformations/tests/test_inline.py
Extending and improving Inline utilities as discussed in #377
> Inline functions (including multi-line and non-elemental functions)

- loki/backend/cgen.py
- loki/ir/expr_visitors.py
- loki/ir/tests/test_expr_visitors.py
- loki/transformations/transpile/tests/test_transpile.py
[TRANSPILATION] handle modulo operator/function for c-like-backends ...
convert
* `MOD(a, b)` to `a % b` for integer parameters/arguments
* `MOD(x, y)` to `fmod(x, y)` for floating point parameters/arguments
> handle modulo operator/function for c-like-backends

- loki/ir/nodes.py
- loki/ir/tests/test_ir_nodes.py
- loki/transformations/sanitise.py
- loki/transformations/tests/test_sanitise.py
~_Note: This PR sits on top of PR #372 and requires this to be merged first._~
This PR re-writes the `ResolveAssociateTransformer` and switches it to acting entirely in-place. For this, instead of finding all symbols and substituting them with their inverse-association, we now simply run over each symbol, find its inverse from the `.scope` and apply in-place. This requires the substitution to be written as a symbol mapper.
As an addition feature, we can now do partial resolution in associate bodies, where only a select sub-region of the code has its associated symbols resolved. I've added a test to this extend.
And on top of that I've refactored the imports in the associated test.
Edit: I've also had a to introduce "auto-fixer" behaviour for `CallStatement` nodes and a corresponding test. …
> Transformations: ResolveAssociateTransformer re-write to in-place substitution

- loki/transformations/inline.py
- loki/transformations/tests/test_inline.py
When inlining functions we need to remove any routine-level pragmas, such as `!$loki routine seq`, so as not to erroneously mark the caller body with them. This change adds a removal step and should hopefully fix ec-physics regression.
> Transformations: Remove routine pragmas when inlining functions

- loki/transformations/__init__.py
- loki/transformations/routine_signatures.py
- loki/transformations/tests/test_routine_signatures.py
Transform/convert e.g., 
```fortran
SUBROUTINE driver (nlon, nlev, nb, var)
USE kernel_mod, ONLY: kernel
IMPLICIT NONE
INTEGER, INTENT(IN) :: nlon, nlev, nb
REAL, INTENT(INOUT) :: var(nlon, nlev, 5, nb)
INTEGER :: ibl
INTEGER :: offset
INTEGER :: some_val
INTEGER :: loop_start, loop_end
loop_start = 2
loop_end = nb
some_val = 0
offset = 1
!$omp test
DO ibl=loop_start,loop_end
CALL kernel(nlon, nlev, var(:, :, 1, ibl), var(:, :, 1, ibl), var(:, :, 2:5, ibl), offset, loop_start, loop_end, nlev)
CALL kernel(nlon, nlev, var(:, :, 1, ibl), var(:, :, 1, ibl), var(:, :, 2:5, ibl), offset, loop_start, loop_end, nlev)
END DO
END SUBROUTINE driver
SUBROUTINE kernel (nlon, nlev, var1, var2, another_var, icend, lstart, lend, kend)
USE compute_mod, ONLY: compute
IMPLICIT NONE
INTEGER, INTENT(IN) :: …
```
> Utility to remove duplicate arguments for calls and callees

- conftest.py
- loki/__init__.py
As discussed offline: This provides a CLI option overwrite for the log-level when running pytest, and removes the duplicate env variable hook from the config.
> Pytest CLI option for log-level

- conftest.py
- loki/__init__.py
- loki/batch/scheduler.py
- loki/batch/sgraph.py
- loki/frontend/fparser.py
- loki/frontend/preprocessing.py
- loki/frontend/util.py
- loki/logging.py
- loki/sourcefile.py
- scripts/loki_transform.py
This PR brings a small clean-up and adjustments of our log-levels in preparation for some scheduler work. In particular it does:
* Introduce a new log-level DETAIL to capture per-file info in a batch processing context. This sits below PERF, so that PERF can be used for scheduler things without completely clobbering things with per-file output
* Docstrings for the specific log-levels to give some rough guidance on how to use them
* Adjustements to most of the frontend and scheduler timer logging; we now only output high-level timers for scheduler actions (no nested info!) and put the nested sub-components on PERF. Similarly, only the heavy IR parse stays at per-file level with PERF (as before with INFO), and all other frontend timers are put to DETAIL.
* The `--log-level` option is added …
> Logging: Small log-level sanitisation and CLI flags 

- loki/batch/tests/test_scheduler.py
- loki/transformations/single_column/__init__.py
- loki/transformations/single_column/scc.py
- loki/transformations/single_column/tests/test_scc_vertical.py
- loki/transformations/single_column/vertical.py
- loki/transformations/tests/test_transform_loop.py
- loki/transformations/transform_loop.py
- scripts/loki_transform.py
Vertical loop fusion and demotion of temporaries in the vertical dimension if possible based on
pragmas in the input source code and heuristics.
This is intended to be a starting point for a more automated and sophisticated approach (including dataflow analysis) as well as further optimisations that require this as a first step.
**To test with CLOUDSC**, checkout branch `nams-vertical-loop-fusion`.
This results in the following performance improvements (executed with `1 262144 128`):
| VARIANT | ORIG/WITHOUT | WITH NEW TRAFO |
| --------- | ---------------- | ------------------- |
| SCC | ca. 200 GF/s | ca. 460 GF/s |
| SCC-HOIST | ca. 320 GF/s  | ca. 500 GF/s |
| SCC-STACK | ca. 320 GF/s | ca. 520 GF/s |
> Vertical loop fusion and demotion of temporaries

- loki/transformations/single_column/annotate.py
- loki/transformations/single_column/tests/test_scc.py
- loki/transformations/single_column/vector.py
- loki/transformations/tests/test_loop_blocking.py
- loki/transformations/utilities.py
Arrays with existing data declarations should not be privatized in the driver gang loop. This PR adds the functionality to gather information from encompassing `!$acc data` regions and filter out the relevant arrays.
> Skip privatization of arrays with existing data declarations

- pyproject.toml
~_Note: Draft PR to trigger tests_~
What it says on the tin:
- Update f90wrap to 0.2.15 as minimum version, which restores compatibility with numpy 2.0 (https://github.com/jameskermode/f90wrap/releases/tag/v0.2.15)
- That allows to remove the restriction numpy<1.24
- Which allows to enable Python 12 as supported Python version
- ...and Python 12 added to the Github actions test matrix
> Update f90wrap to 0.2.15 as minimum to ensure compatibility with numpy 2.0+

- loki/transformations/single_column/annotate.py
- loki/transformations/single_column/tests/test_scc.py
PR #389 introduced a regression in ecphys. There we have an ACC statement like this:
```
!$acc data copyin(var_a, var_b) &
!$acc &    copyin(var_c) create(var_d)
```
Now, the ACC statements are checked for existing offload directives. For that, `get_pragma_parameters` is used to extract offload "categories". However, for situations where a key exists more than once, the values are provided as a list, i.e., for the above we obtain
```
{'copyin': ['var_a, var_b', 'var_c'], 'create': 'var_d'}
```
Where previously a simple `str.split(',')` was used to build a list of variables of each category, we need to be careful to accomodate for the above situation where not a simple string constitutes the value. This PR expands the test to include the above case and fixes the transformation accordingly.
> Fix SccAnnotate when existing acc pragmas declare a copy category more than once

- loki/backend/tests/test_fgen.py
- loki/frontend/fparser.py
- loki/frontend/ofp.py
- loki/frontend/omni.py
This was triggered by the fgen issue reported in #393. This looked first like the issue was simply that we did not account for the case that procedure information might be missing when generating the code for procedure declarations.
However, while trying to sort this out across frontends, I noticed that it should be perfectly possible to recognize the interface as a procedure in this situation, and that the handling of procedure types for symbols declared in procedure declarations was very inconsistent and partially wrong. This should fix this discrepancy.
> Improve representation of procedure pointers (fix #393)

- loki/frontend/fparser.py
- loki/logging.py
- loki/transformations/inline/mapper.py
- loki/transformations/inline/tests/test_functions.py
This adds the missing test for `InlineSubstitutionMapper`, expanded to four different cases:
1. Inline call provided as a module import, module available
2. Inline call provided as a module import, module not available
3. Inline call provided via an interface block
4. Inline call provided via an interface that is imported via c preprocessor (i.e., no interface available)
This includes a small fix to the mapper for the third case, where procedure information is available but that referes only to the interface, i.e., no body for inlining is present.
Let's see what codecov says...
> Fix function inlining when only interface is available (fixes #397)

- .github/workflows/regression_tests.yml
- loki/transformations/tests/test_cloudsc2_tl_ad.py
This adds a regression test for CLOUDSC2 processing, and enables it as part of the Github actions CI tests.
Temporarily, it points to a branch for CLOUDSC2, which has a pending PR for integration: ecmwf-ifs/dwarf-p-cloudsc2-tl-ad#14
The PR is filed against the new Scheduler branch but doesn't have to be integrated now and can be left dangling for the moment.
Processing works fine and results are correct with GNU on host-side (GPU evaluation is tbd), however, in the Actions runner I'm seeing randomly massive deviations for steps 4 and 6 in the TL variant. No clue what is going on there.
> Regression test for CLOUDSC2

- loki/frontend/fparser.py
- loki/ir/nodes.py
- loki/ir/tests/test_ir_nodes.py
- loki/tools/util.py
- loki/transformations/sanitise.py
- loki/transformations/tests/test_sanitise.py
~_Note: This sits on top of PR #387 and requires this to be merged first._~
This PR adds a new utility to merge `Associate` blocks and adds a feature to the existing `resolve_associations` method to restrict the starting depth of the association resolution. Combining the two allows for a neat look and feel, where all except the first layer of (non-nested) associations get resolved after all non-nested ones have been merged into the outermost associate block. Tests have been added for both features.
Edit: This one took on a life of its own after the interior mechanics of `ResolveAssociates` were changed ( PR #387 ). As the new resolver relies very strictly on identifying the "depth" via finding the defining scope, the new merge mechanism needs to carefully update the changes scopes to …
> Utilities to merge associate blocks and restrict depth of associate resolution

- loki/transformations/tests/test_ecwam.py
The ecwam-bundle project name in the regression test is outdated, which lead to the tagged loki release in the ewam bundle being cloned everytime the test was run. Since `--without-loki-install` is specified, that version is never built and the local copy of loki is indeed used. Nevertheless it would be good to prevent an unnecessary clone of loki during the regression test.
> Prevent superfluous clone of loki in ecwam regression test

- loki/transformations/inline/functions.py
- loki/transformations/inline/tests/test_functions.py
We have a problem for things like:
```fortran
elemental function elem(x, y)
real :: x, y, elem, tmp
temp = y * 2.0
elem = x + tmp
end function elem
real :: x_scalar, b_scalar, res_scalar
real :: x_arr(10). y_arr(10), res_arr(10)
real :: x_arr_2(12). y_arr_2(12), res_arr_2(12)
res_scalar = elem(x_scalar, y_scalar)
res_arr = elem(x_arr, y_arr)
res_arr = elem(x_arr, y_scalar)
res_arr = elem(y_scalar, x_arr)
res_arr_2 = elem(x_arr_2, y_arr_2)
...
```
As the fix is not straight-forward/trivial, this PR makes the inline to skip the problematic calls (for now). Thus, **this is not a fix to make those problematic calls being inlined correctly!**
A more detailed description of the problem: #400
> Inline elemental functions: skip calls with args being array (slices)

- loki/backend/tests/test_fgen.py
- loki/backend/tests/test_pygen.py
- loki/batch/tests/test_scheduler.py
- loki/expression/tests/test_expression.py
- loki/frontend/ofp.py
- loki/frontend/preprocessing.py
- loki/frontend/tests/test_frontends.py
- loki/frontend/util.py
- loki/ir/tests/test_control_flow.py
- loki/sourcefile.py
- loki/tests/test_derived_types.py
- loki/tests/test_modules.py
- loki/tests/test_sourcefile.py
- loki/tests/test_subroutine.py
- loki/tests/test_types.py
- loki/transformations/build_system/tests/test_dependency.py
- loki/transformations/extract/tests/test_extract_internal.py
- loki/transformations/inline/tests/test_functions.py
- loki/transformations/inline/tests/test_inline_transformation.py
- loki/transformations/single_column/tests/test_scc.py
- loki/transformations/tests/test_cloudsc.py
- loki/transformations/tests/test_pool_allocator.py
- loki/transformations/transpile/tests/test_transpile.py
~_Note: Just testing for now..._~
As described in #209 , this PR deprecates the OFP frontend and adds a warning to the central OFP parse method. It also purges the `OFP` symbol from the outward-facing API and the test base (including the `available_frontends()` utiltiy), leaving internal mechanics to rely on the explicit mention of `Frontend.OFP`.
Please note that the frontend itself is still present and functional, but it's use is now discouraged.
> Frontend: Deprecate OFP and purge from test base

- cmake/python_venv.cmake
A small hotfix PR that removes the "Development" component from the find_package for Python in a CMake installation.
This component is intended to allow applications to use Python headers - but Loki, as a pure Python package, doesn't need this. However, the find_package will fail if Python headers cannot be found, thus preventing installation.
> CMake/python_venv: Do not request COMPONENT Development

- loki/frontend/fparser.py
- loki/frontend/tests/test_frontends.py
Infer shape via Loki dimension pragmas, e.g.,
```fortran
!$loki dimension(x/2, x**2, (x+y)/x)
real(kind=jprb), dimension(:, :, :), pointer :: v6 
```
not only for routines but also for modules (FP only).
> Handle Loki dimension pragmas for modules (and not only routines) for FP

- loki/transformations/tests/test_utilities.py
- loki/transformations/utilities.py
necessary for 'convert_to_lower_case' functionality.
@reuterbal it is unfortunately not possible without further changes to move the `with config_override` out of `recursive_expression_map_update` since the case-sensitivity produces problems within that function beyond the check for early termination.
> Allow for optional case-sensitive 'recursive_expression_map_update'

- loki/backend/cgen.py
- loki/transformations/transpile/tests/test_transpile.py
For now: just don't generate code for Fortran interfaces when applying c-like-backends (`cgen`, `cppgen`, `cudagen`).
> C-like-backends: skip/don't write Fortran interfaces

- loki/batch/scheduler.py
- loki/batch/tests/test_transformation.py
- loki/transformations/build_system/file_write.py
- scripts/loki_transform.py
A small PR that turns the builddir into a runtime argument of the `FileWriteTransformation`. This allows the builddir to be passed in via command line arguments even if the `FileWriteTransformation` is being overridden via a scheduler config.
> Make builddir a runtime argument of `FileWriteTransformation`

- scripts/loki_transform.py
Pretty much what it says on the tin: adding a deprecation warning at the entry-point in `loki-transform.py convert` where we are planning to remove support for internally specified transformations. Once config-only mode is ready to be enforced, everything after this warning can.
_Integration note: Please announce this on the respective collaboration channels to make users aware._
Follow-on thought: Once enforced, I would like to add an alias `--pipeline`/`-p` for the `--mode`/`-m` CLI option, but that would require a lot of CMake-level renaming. Would this be useful, or overkill, @reuterbal ?
> Loki-transform: Add deprecation message about custom entry points

- loki/expression/mappers.py
- loki/expression/symbolic.py
- loki/expression/symbols.py
- loki/expression/tests/test_expression.py
- loki/expression/tests/test_mapper.py
- loki/expression/tests/test_parser.py
- loki/expression/tests/test_symbolic.py
- loki/expression/tests/test_symbols.py
- loki/frontend/util.py
- loki/ir/expr_visitors.py
- loki/subroutine.py
- loki/transformations/utilities.py
~_Note: Only for testing so far ..._~
The primary intention behind this PR is to increase test coverage of the expression mappers and rigorously duplicate symbols when expression mappers (`LokiIdentityMapper` and `SubstituteExpressionMapper`). It also fixes a bunch of other issues along the way that this threw up and now fixes #379 .
In a little more detail:
* Add dedicated tests for expression walker (via `ExpressionRetriever`) and the mappers `LokitIdentityMapper` and `SubstituteExrpressionMapper`
* Lint-clean the expression tests directory
* Remove the now redundant `invalidate_source` argument from Loki mappers (we do not store source on expressions anymore)
* Fix the resulting issue in `recursive_expression_map_update` by checking for ancestry of `SubstituteExpressionMapper` before …
> Expression: Expression cloning and mapper tests

- loki/ir/pragma_utils.py
- loki/ir/tests/test_pragma_utils.py
The problem are false matches if "end" appears in pragma content after the initial `end` keyword.
This should also fix issue #427
> IR: Fix false "end" matches in pragma_regions_attached utility

- example/03_loop_fusion.ipynb
- loki/transformations/remove_code.py
- loki/transformations/single_column/vertical.py
- loki/transformations/tests/test_transform_loop.py
- loki/transformations/transform_loop.py
A transformation to run the loop transform utilities in a specified order, with the aim to place this transformation in scheduler pipelines.
> Transformation to call loop transform utilities

- lint_rules/lint_rules/debug_rules.py
- loki/transformations/block_index_transformations.py
- loki/transformations/inline/procedures.py
- loki/transformations/sanitise/__init__.py
- loki/transformations/sanitise/associates.py
- loki/transformations/sanitise/sequence_associations.py
- loki/transformations/sanitise/substitute.py
- loki/transformations/sanitise/tests/test_associates.py
- loki/transformations/sanitise/tests/test_sanitise.py
- loki/transformations/sanitise/tests/test_sequence_associations.py
- loki/transformations/single_column/base.py
- loki/transformations/single_column/scc_cuf.py
- loki/transformations/tests/test_transform_derived_types.py
- loki/transformations/transpile/fortran_c.py
- loki/transformations/transpile/fortran_python.py
This PR creates a new transformation sub-package for sanitisation and then refactors and improves several of the existing utilities for easier inclusion in external pipelines.
In particular it separate associate-handling from sequence-association resolution, and adds a new utility for user-driven expression substitution. Each of those are now available as a single `Transformation` object and have been combined into a combined `SanitisePipeline`, each of which can now be used via external config constructors. The existing `SanitiseTransformation` is retained for backward compatibility.
In some more detail:
* Created a new sub-package `loki.transformations.sanitise` and moved according tests. In this sub-package, existing utilities for associates and sequence association have been separated …
> Sanitise: New transformation sub-package and some refactoring

- loki/ir/pragma_utils.py
- loki/transformations/__init__.py
- loki/transformations/parallel/__init__.py
- loki/transformations/parallel/block_loop.py
- loki/transformations/parallel/field_api.py
- loki/transformations/parallel/openmp_region.py
- loki/transformations/parallel/tests/test_block_loop.py
- loki/transformations/parallel/tests/test_field_api.py
- loki/transformations/parallel/tests/test_openmp_region.py
_Note: This sits on top of #414 , as it requires the new `Dimension` overloading mechanism for block-loop dimensions._
This change brings a set of utilities that form the basis of "driver"-level control flow manipulation for IFS-style block loops, OpenMP parallel regions and FIELD API boilerplate code. They are loose packaged in a new sub-module `loki.transformations.parallel` and are intended to be extended at a later stage. The come in remove / add pairs, and currently only pertain to host-side driver loops with FIELD-API view updates.
I've also piggy-backed two small IR-level fixes (logging string and a weird corner case for pragma region detection), the latter of which was needed for some of the testing of the new functionalities.
In a little more detail, the new sub-package provides: …
> Transformations: "Parallel" sub-module with driver-level parallelilsation utilities

- cmake/loki_transform_helpers.cmake
- loki/backend/tests/test_fgen.py
- loki/tools/strings.py
- loki/tools/tests/test_tools.py
The line break heuristic in JoinableStringList did not account for quoted strings, sometimes putting line breaks into the middle of a string.
This caused issues with an initialiser list for a character array, where the list entries contained white spaces.
The fix is to search for quoted strings in the remainder string and treat them as unbreakable entities, while retaining the same splitting heuristic as before outside of quoted strings. This allowed to remove a four year old "TODO" comment that points out that the above problem might occur... 🤦 
Two tests are included to validate the behaviour directly on the class as well as in the original Fortran context where the problem first occured.
Piggy-backed is also a small hotfix to the CMake layer to fix an issue that occured if no frontend …
> JoinableStringList: Do not break lines within quoted strings

- loki/backend/cudagen.py
- loki/expression/symbols.py
- loki/expression/tests/test_expression.py
- loki/ir/nodes.py
- loki/tests/test_subroutine.py
- loki/transformations/block_index_transformations.py
- loki/transformations/single_column/scc_cuf.py
- loki/transformations/tests/sources/projSccCuf/module/kernel.f90
- loki/transformations/transpile/fortran_c.py
- loki/transformations/transpile/tests/test_transpile.py
Mostly related to nested/multi-level kernel calls:
* `__device__` prefix
* kwargs to args (also for inline calls)
* call name adaptation -> `<call/function name>_c`
* ...
> Continued: F2C/CUDA transpilation

- loki/transformations/data_offload.py
- loki/transformations/parallel/field_api.py
- loki/transformations/parallel/tests/test_field_api.py
- loki/transformations/tests/test_data_offload.py
This adds a new transformation, ``FieldOffloadTransformation``,   for offloading F-API fields to GPU. Specifically this transformation is meant to operate on CPU driver code that passes view pointers to the kernels. The transformation
1. Removes the view update calls
2. Adds new device pointers for the arrays to offload
3. Adds F-API data offload and sync calls
4. Replaces the old *view-based* arguments in kernel calls with device pointer slices
The corresponding ``dwarf-p-cloudsc`` implementation is on the branch [dwarf-p-cloudsc/je-field-api-offload-v2](https://github.com/ecmwf-ifs/dwarf-p-cloudsc/tree/je-field-api-offload-v2). This adds a new transformation pipeline for converting view based CPU driver code to GPU offloaded F-API code,  ``[pipelines.scc-field]``, and a new Loki target …
> DataOffload: Add new FieldOffloadTransformation for FIELD API boilerplate injection

- loki/batch/item.py
- loki/expression/mappers.py
- loki/expression/tests/test_expression.py
- loki/frontend/fparser.py
- loki/frontend/omni.py
- loki/frontend/tests/test_frontends.py
- loki/ir/tests/test_visitor.py
- loki/tests/test_modules.py
- loki/transformations/tests/test_raw_stack_allocator.py
- loki/types.py
- pyproject.toml
This PR adds handling of intrinsic function calls by adding an `is_intrinsic` property to `ProcedureType` and adding the procedure type to the parsing scope in frontends before creating the respective `ProcedureSymbol`.
We also add the new `is_intrinsic` flag to the symbol attributes table for quick lookup in scheduler items, as we never want to chase intrinsics.
EDIT: This also needs the fix from #439 and needs a rebase once that is merged.
> Expressions: Handle intrinsic function calls

- loki/expression/mappers.py
- loki/transformations/inline/procedures.py
- loki/transformations/inline/tests/test_functions.py
This caused problems by a race condition, where the elemental scope that was the original scope of intrisincs could be re-build, making the scope weakref invalid before the final catch-all rescoping.
To fix this, I'm explicitly foxing the function body to be rescoped, before it gets inserted. This was problematic, as intrisic procedure symbols were not updated correctly, so I enforce indiscriminant rescoping for intrisic procedure symbols to the given, closest scope in `AttachScopesMapper`.
> Inline: Fix rescoping of intrinsic procedure symbols in elementals

- loki/transformations/data_offload.py
- loki/transformations/tests/test_data_offload.py
A small fix to how the global variable offload pragmas are generated which allows them to be split into multiple lines by `fgen`.
> DataOffload: fix generation of offload pragmas

- loki/transformations/tests/test_transform_loop.py
- loki/transformations/transform_loop.py
This PR provides the following two fixes to the loop unrolling functionality:
- Unroll loops with negative bounds
- Retain pragmas inside the unrolled loop body
> Unroll negative loop bounds and retain pragmas inside unrolled loop body

- loki/analyse/tests/__init__.py
- loki/backend/tests/__init__.py
- loki/backend/tests/test_fgen.py
- loki/batch/tests/__init__.py
- loki/batch/tests/test_batch.py
- loki/batch/tests/test_transformation.py
- loki/build/tests/__init__.py
- loki/build/tests/test_build.py
- loki/expression/tests/__init__.py
- loki/frontend/tests/__init__.py
- loki/ir/tests/__init__.py
- loki/ir/tests/test_control_flow.py
- loki/ir/tests/test_ir_nodes.py
- loki/ir/tests/test_pragma_utils.py
- loki/ir/tests/test_scoped_nodes.py
- loki/program_unit.py
- loki/tests/__init__.py
- loki/tests/test_dimension.py
- loki/tests/test_modules.py
- loki/tests/test_subroutine.py
- loki/tools/tests/__init__.py
This make test integration cleaner and avoids eventual namespace clashes in the future. It also now runs the linter over tests, without exporting test symbols as part of `from loki import *` (please double-check this). 
Note, the other half of this is hidden in PR #446 , where this was necessary to avoid namespace clashes in tests.
EDIT: Looks like I have to leave `loki.lint.tests` untouched, as the introduction of the test sub-packages makes the dynamic `rules` imports go haywire. I leave that for a follow-on PR.
> Loki: Turn test sub-directories into sub-pacakges

- loki/program_unit.py
- loki/tests/test_modules.py
This addresses issue #428 . Many thanks to @wertysas for the excellent reproducer and test
The problem was essentially that we would drop type info for subroutines if the info enrichment came though type imports on the parent `Module`. This is easily fixed by including parent imports in the enrichment loop over Imports.
I took the opportunity to also clean up the import on `test_module.py` in the process.
> Module: Fix enrichment of type info via `Module` imports

- loki/batch/scheduler.py
- loki/batch/sgraph.py
- loki/batch/tests/test_scheduler.py
- loki/program_unit.py
- loki/transformations/build_system/file_write.py
- loki/transformations/build_system/tests/test_file_write.py
- scripts/loki_transform.py
This fixes two errors spotted with complex Fortran module dependencies:
1. When including module files in transformations, we had inconsistent behaviour between the files in a dependency graph that are going to be written, and those that are listed in the CMake plan. 74409002d6bd05e83504804806a92ae393e17186 applies the methodology that is used to derive the file graph for the `FileWriteTransformation` also when deriving the file list in the CMake plan writing, thus ensuring consistent behaviour.
2. For indirect imports, e.g., when importing a symbol from a module, where the symbol itself is only available because of an import from a third module, enrichment failed non-gracefully because we had the presumed origin module available but that module didn't have the symbol information …
> CMake plan and enrichment bugfix

- loki/transformations/transpile/fortran_c.py
- loki/transformations/transpile/tests/test_transpile.py
Convert interface to kernel calls (e.g., `interface kernel ...`) to the appropriate import (e.g., `kernel_fc_mod, only: kernel_fc`).
> [F2C transpilation] (driver level) convert interface to import

- loki/transformations/array_indexing.py
- loki/transformations/tests/test_array_indexing.py
Imagine having
```fortran
INTEGER :: ARR(N)
ARR(:) = 1
ARR(1:5) = 1
DO J=1,N
...
ENDDO
```
This would have been transformed to
```fortran
DO JL=1,N
ARR(JL) = 1
ENDDO
DO JL=1,N
ARR(JL) = 1
ENDDO
```
With this PR it is instead transformed to:
```fortran
DO JL=1,N
ARR(JL) = 1
ENDDO
DO i_arr_0=1,5
ARR(i_arr_0) = 1
ENDDO
```
or if a loop `DO JL=1,5` exists to:
```fortran
DO JL=1,N
ARR(JL) = 1
ENDDO
DO JL=1,5
ARR(JL) = 1
ENDDO
```
> resolve_vector_notation: fix/improvement

- loki/batch/configure.py
- loki/batch/item.py
- loki/batch/tests/test_batch.py
While profiling the building of the SGraph, I noticed two things:
1. A non-negligible amount of time was spent on checking if items are part of any of the exclusion lists. The reason that this is costly is the pattern support, which incurs some overhead for repeatedly compiling search patterns. This can be partially reduced by using `fnmatch.filter` instead of a comprehension with `any`. On top of that, I tried reducing the amount of pattern compilations overall via some reordering or caching, however, since `fnmatch` already comes with a built-in pattern cache, this did worsen performance in all cases.
2. The `Module` class includes module variables in the list of definitions, which is correct from a Fortran point-of-view but not required for the Scheduler, where we don't capture …
> SGraph (re-)build optimisations

- loki/batch/scheduler.py
- loki/batch/tests/test_scheduler.py
- loki/batch/transformation.py
- loki/tests/test_cmake.py
- loki/transformations/build_system/file_write.py
- loki/transformations/build_system/plan.py
- loki/transformations/build_system/tests/test_file_write.py
- scripts/loki_transform.py
This is an alternative implementation suggestion to #444 
The objective here would be to retain current functionality and implement support for transformations that change scheduler graph topology in subsequent PRs.
Please have a look and point out anything that looks odd to you. In particular, please consider the interface - e.g., is a `plan` argument acceptable and the naming ok?
With this, the `loki-transform.py plan` command is redirected to the `loki-transform.py convert` command, clearing the way for subsequent removal of the custom transformation entry point and further homogenisation in the CLI and CMake layer.
I will also add another commit to add some more documentation (and I expect the linter pass to fail due to the local import).
> CMake Plan: Pipeline dry-run and transformation-based plan creation

- loki/transformations/sanitise/associates.py
- loki/transformations/sanitise/tests/test_associates.py
The current `Associate` resolution does not account for array index ranges if they are specific in the associate clauses (index remapping). This PR adds a partial resolution step to `ResolveAssociates`, which resolves free index ranges (`:`) in association clause against explicit indices from the original expression, should should both exist. The respective changes in the expression mapper require some care with respect to early termination and recursion into `.dimension` and `.type` properties of the given array expression.
Note: It does not resolve index shifts, where offsets are introduced by using bounded ranges (eg. `3:8`). Instead it warns about such (ab)use.
> Sanitise: Resolve free range indices when resolving associates

- loki/transformations/build_system/dependency.py
- loki/transformations/build_system/tests/test_dependency.py
rename/transform private/public access specifiers for modules
@reuterbal and @mlange05: asking for feedback on this
problem for OMNI:
```
item_name = f'#{proc_name}'.lower()
if self._is_ignored(item_name, config, ignore):
return None
if config and config.is_disabled(item_name):
return None
if item_name not in self.item_cache:
if not config or config.default.get('strict', True):
>               raise RuntimeError(f'Procedure {item_name} not found in self.item_cache.')
E               RuntimeError: Procedure #kernel_3 not found in self.item_cache.
```
> extending dependency trafo to access specs

- loki/transformations/inline/mapper.py
- loki/transformations/inline/tests/test_functions.py
The stmt function inliner does not actually test the case where the stmt function contains calls to intrinsics. This PR remedies this and fixes the corner case by including explicitly marked intrinsic calls in the skip condition.
This caused issue when the following lines attempt to touch the non-existent procedure definition.
> Inline: Skip explicit intrinsics when inlining stmt functions

- loki/expression/symbolic.py
- loki/expression/tests/test_symbolic.py
The current implementation would only resolve .and./.or. operations if all arguments are logical literals. Instead, we can evaluate `.true. and a` => `.true.` and `.false. and a` => `a`, and vice versa for `or` operations. This allows us to further trim code paths in dead code elimination where this is used to remove conditionals.
> Expression: Remove logical literals in and/or operations during simplify

- loki/transformations/inline/procedures.py
- loki/transformations/inline/tests/test_procedures.py
The previous logic does not account for the same import modules being used by multiple callees, as it attempts to propagate imported symbols in one go. Instead, we now call a utility method for each callee, so that the previous redundancy mechanics avoid duplication across multiple callees, not just between caller and callee.
> Inline: Avoid Import duplication from multiple callees

- loki/transformations/sanitise/associates.py
- loki/transformations/sanitise/tests/test_associates.py
When nested associates are about to be removed, we need to account for that when updating the symbol-scope (a priori). This new logic does this by counting out the nested associates and picking the appropriate one, according to the septh of the symbol in the nest.
I've extended the stat-func test, where this most often triggers.
Note, this looks like a recurrence of the problem in #439 and hopefully should address issue #459 (@ecossevin to confirm).
> Sanitise: Fix rescoping of symbols for nested associates

- cmake/loki_transform.cmake
There was a typo in the variable name, possibly causing race conditions in parallel build when a header module is also generated.
> Fix dependency on header files in loki_transform_target

- loki/transformations/tests/test_utilities.py
- loki/transformations/utilities.py
Nested calls to functions is not captured in `convert_to_lower_case`, which can break the Fortran-to-Python converter. This simple fix remedies this.
> Transformations: Fix downcasing of nested `InlineCall` symbols

- loki/ir/nodes.py
- loki/ir/tests/test_ir_nodes.py
Instead of using `model_validator` objects, we can use inidividual `field_validator` utilities to do per-argument auto-casting. The effect of this is that we can then use positional constructor arguments without using the funcationality and dealing the full model `ArgsKwargs` objects.
This should address issue #420, @wertysas to confirm.
> IR: Better tuple autocasting via pydantic field_validators

- cmake/loki_transform.cmake
- cmake/loki_transform_helpers.cmake
- scripts/loki_transform.py
~_Note: This sits on top of PR #464 and requires CLOUDSC  CLOUDSC PR 106 to be merged first._~
~_Note: For testing only at this stage._~
Following the conversion to config-file based pipelines, this PR now removes all the custom entry point options under `loki-transform.py convert` and their associated use in CMake macros. It also removes the now unused `loki_transform_convert` entry point.
> Loki-transform: Remove custom entry point options

- loki/transformations/data_offload/field_offload.py
- loki/transformations/data_offload/tests/test_field_offload.py
Turns out in our CLOUDSC regression test we were not yet testing the new FIELD-API generation transformation, and it was broken. 🙀 The issue was that there are several calls to timer routines that are harmless, but break the rigorous sanity checks. So, instead of breaking we now warn ans kip, and enable the test in the regression suite.
> FieldOffload: Allow and skip non-enriched calls in offload region

- loki/transformations/pool_allocator.py
- loki/transformations/tests/test_pool_allocator.py
We already handled range indices like e.g., `0:10` properly as long as those aren't the first dimension/shape ...
Thanks @piotrows for pointing this out!
> PoolAllocator: fix handling of first shape/dimension being a range index

- loki/transformations/pool_allocator.py
- loki/transformations/tests/test_pool_allocator.py
improvement so that stack size calculation and incrementing guarantees 8 byte alignment.
With this, 
```fortran
ISTSZ = (C_SIZEOF(REAL(1, kind=JPRB))*NPROMA + 13*C_SIZEOF(REAL(1, kind=JPRB))*NLEV*NPROMA + 5*C_SIZEOF(REAL(1, kind=JPRB)) &
& *NLEV*NPROMA*NCLV + C_SIZEOF(REAL(1, kind=JPRB))*NPROMA*NCLV) / C_SIZEOF(REAL(1, kind=JPRB))
IF (.not.(MOD(C_SIZEOF(REAL(1, kind=JPRB))*NPROMA + 13*C_SIZEOF(REAL(1, kind=JPRB))*NLEV*NPROMA + 5*C_SIZEOF(REAL(1,  &
& kind=JPRB))*NLEV*NPROMA*NCLV + C_SIZEOF(REAL(1, kind=JPRB))*NPROMA*NCLV, C_SIZEOF(REAL(1, kind=JPRB))) == 0)) ISTSZ = ISTSZ &
&  + 1
```
becomes:
```fortran
ISTSZ = ISHFT(7 + C_SIZEOF(REAL(1, kind=JPRB))*NPROMA + C_SIZEOF(REAL(1, kind=JPRB))*NLEV*NPROMA, -3) + 12*ISHFT(7 +  &
& C_SIZEOF(REAL(1, kind=JPRB))*NLEV*NPROMA, -3) + 4*ISHFT(7 + …
```
> PoolAllocator improvement

- loki/frontend/fparser.py
- loki/frontend/tests/test_frontends.py
- loki/transformations/argument_shape.py
- loki/transformations/tests/test_argument_shape.py
This PR adds support for assumed size declarations (😑 ) for Fparser, and also adds the mechanics to the `ArgumentShapeAnalysis` to resolve the corresponding explicit shape.
> Add support for assumed size declarations to Fparser

- loki/batch/item.py
- loki/batch/tests/test_scheduler.py
We had this situation as an x-failing test previously, leaving open the question how to handle calls to internal member procedures when building the Scheduler's SGraph. But as discussed offline, since internal member procedures are fully contained within their enclosing parent routine, it does not make much sense to add them explicitly to the scheduler's dependency graph. For the SCC adaptation recipes, we typically inline those anyway.
The implication is of course that the Scheduler's processing of transformation pipelines will by default not include internal member routines, which is also the current behaviour. However, if we were to introduce transformations that were to specifically require processing of internal member procedures in the future, this should likely be achieved via the …
> Exclude calls to contained member procedures from dependencies

- loki/batch/scheduler.py
- loki/batch/tests/test_scheduler.py
This change allows individual source file locations to be added without resorting to directory globs. This is particularly useful for auto-inlining individual external utility routines, without having to search their entire parent location during discover.
This extends one of the existing tests instead of adding a new one.
> Scheduler: Allow explicit file paths to be added as sources

- loki/batch/tests/test_scheduler.py
- loki/transformations/single_column/scc.py
- loki/transformations/single_column/tests/test_scc.py
- loki/transformations/single_column/tests/test_scc_hoist.py
- loki/transformations/single_column/tests/test_scc_vector.py
- loki/transformations/single_column/vector.py
New/additional SCC revector transformation that hoists the horizontal loop to the driver and passes the horizontal/loop variable to the kernel(s).
> SCC revector transformation that gives sequential kernels

- loki/transformations/inline/procedures.py
- loki/transformations/inline/tests/test_inline_transformation.py
A small fix to the inlining trafo that enables inlining of calls where we pass a subrange of an array argument, i.e.:
```
real :: a(8)
!$loki inline
call kernel(a(5:8)
....
subroutine kernel
real, intent(in) :: a(4)
```
> Enable inlining of a subroutine with an array subrange in an argument

- .github/workflows/regression_tests.yml
- .github/workflows/tests.yml
- .gitignore
- CMakeLists.txt
- conftest.py
- install
- loki/build/compiler.py
- loki/build/obj.py
- loki/build/tests/test_build.py
- loki/frontend/tests/test_frontends.py
- loki/lint/tests/test_linter.py
- loki/tests/test_derived_types.py
- loki/tests/test_modules.py
- loki/transformations/inline/tests/test_constants.py
- pyproject.toml
The distutils build system that underpinned the f90wrap-f2py JIT compilation used in Loki's test base was deprecated a while ago - and Python 3.12+ now ship with a version that no longer supports this. For that reason, Numpy 2+ (f2py) and f90wrap have switched to a Meson build backend. We put off adapting to this for a while and it has now become a problem.
This PR remedies this via the following changes:
- `loki.build` has been modified to use the Meson build backend. To get this to work, I had to change the previous invocation of `f2py-f90wrap` to providing the .F90 instead of a .o file.
- Numpy version requirement has been updated to version >= 2.0 to ensure the availability of the meson build backend in f2py. 
- However, Numpy 2 only has support for Python 3.9+, so I had to disable …
> Python 3.12/3.13 compatibility

- loki/batch/sfilter.py
- loki/batch/tests/test_scheduler.py
Fix for #497.
Thanks @reuterbal!
> SFilter: fix for external and ignored items

- loki/transformations/dependency.py
- loki/transformations/tests/test_dependency.py
Duplicating a kernel and optionally duplicating/separating the underlying subgraph.
E.g., starting with:
the result of the DuplicateKernel trafo with duplicate_kernels=('kernel',) is:
However, with this PR one can specify duplicate_subgraph=True, which yields for the example above:
> optionally duplicating/separating the underlying subgraph when duplicating item/call 

- docs/source/loki_pragma_model.csv
- docs/source/programming_models.rst
- loki/batch/tests/test_scheduler.py
- loki/ir/pragma_utils.py
- loki/transformations/__init__.py
- loki/transformations/data_offload/global_var.py
- loki/transformations/data_offload/offload.py
- loki/transformations/data_offload/tests/test_global_var.py
- loki/transformations/data_offload/tests/test_offload.py
- loki/transformations/pool_allocator.py
- loki/transformations/pragma_model.py
- loki/transformations/raw_stack_allocator.py
- loki/transformations/single_column/annotate.py
- loki/transformations/single_column/base.py
- loki/transformations/single_column/hoist.py
- loki/transformations/single_column/scc.py
- loki/transformations/single_column/scc_cuf.py
- loki/transformations/single_column/tests/test_scc.py
- loki/transformations/single_column/tests/test_scc_hoist.py
- loki/transformations/single_column/vector.py
- loki/transformations/tests/test_pool_allocator.py
- loki/transformations/tests/test_pragma_model.py
- loki/transformations/tests/test_raw_stack_allocator.py
- loki/transformations/tests/test_scc_cuf.py
Introduce 'PragmaModelTransformation' and preliminary OpenMP offload
With this all transformation insert "generic" loki pragmas which are then transformed/mapped as (one of the last steps) using the 'PragmaModelTransformation'  to a specific Pragma model (e.g., OpenACC, OpenMP offload).
> Introduce 'PragmaModelTransformation' and preliminary OpenMP offload

- AUTHORS.md
- loki/frontend/fparser.py
- loki/frontend/tests/test_frontends.py
As mentioned in #510 , symbols listed in `private_access_spec` and `public_access_spec` of modules are not analyzed when importing symbols from other modules. This PR proposes a fix for the issue. I can add a specific unit test if needed
> Check access-spec lists when importing symbols from modules

- loki/frontend/fparser.py
- loki/frontend/omni.py
- loki/frontend/tests/test_frontends.py
This simple PR tries to resolve the bug mentioned in #504.
Tell me if some unit tests for this case are necessary in your opinion.
> Fix: Invalid parsing of empty PRINT statements with fparser

- conftest.py
- loki/frontend/tests/test_frontends.py
- loki/jit_build/compiler.py
- loki/tests/test_derived_types.py
As described in issue #494 the f90wrap step of our built-in JIT compiler does has started having problems with the recent switch to meson. This PR fixes this by adding a dedicated compilation step of the pure Fortran sources into a small, static utility lib that then gets linked into the dynamic lib alongside the wrappers by `f2py-f90wrap`. This follows the internal examples of 90wrap.
> Fix JIT tests with derived types

- cmake/loki_find_executables.cmake
- cmake/loki_python_macros.cmake
- loki/tests/test_cmake.py
The changes by the recently merged #523 cause a problem if Loki is installed with a relative prefix path (i.e., `cmake --install <builddir> --prefix <relative/path>`), leaving the symlinks from `<prefix>/bin` into the installed venv dangling.
This fixes the issue and adds testing for this use case.
> Fix symlink to loki scripts after CMake installation when a relative prefix path was used

- cmake/loki_python_macros.cmake
Otherwise, `cmake --install` will not work if used from a tarball instead of a git worktree. This breaks Github Actions for packages that use Loki at the moment.
> Hotfix: Set SETUPTOOLS_SCM_PRETEND_VERSION during installation if required

- docs/source/internal_representation.rst
- lint_rules/lint_rules/ifs_coding_standards_2011.py
- loki/analyse/analyse_dataflow.py
- loki/analyse/tests/test_analyse_dataflow.py
- loki/backend/fgen.py
- loki/backend/pprint.py
- loki/backend/tests/test_fgen.py
- loki/backend/tests/test_stringifier.py
- loki/frontend/fparser.py
- loki/frontend/tests/test_frontends.py
- loki/ir/nodes.py
- loki/ir/transformer.py
- loki/tools/strings.py
- loki/tools/tests/test_tools.py
- loki/transformations/single_column/vector.py
This is a bugfix PR for a line continuation problem I was facing. In the end it turned out to be the 1-character fix in 0ff12f700de0f5a08a85bf9d00cf4dc45c10387c that was missing, but to get to that realization I implemented a TypeConditional node and a safeguarding against excessive indentation in JoinableStringList. So, we have those now, too.
> Fix indentation in fgen after Associate blocks and add TypeConditional node

- loki/expression/symbols.py
- loki/expression/tests/test_parser.py
```py
>>> from loki import parse_expr
>>> expr = parse_expr('.FALSE.')
>>> expr
LogicLiteral(False)
>>> assert expr
>>> print(bool(expr))
True
```
since the normal behaviour is to return True whenever a Node/expression exists.
With this PR:
```py
>>> from loki import parse_expr
>>> expr = parse_expr('.FALSE.')
>>> expr
LogicLiteral(False)
>>> assert expr
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
AssertionError
>>> print(bool(expr))
False
```
> Introduce '__bool__' method for LogicLiterals

- cmake/loki_transform.cmake
- loki/frontend/preprocessing.py
- loki/frontend/tests/test_fparser_source.py
- loki/frontend/tests/test_regex_frontend.py
A small PR that turns the functionality of updating a target's sources into a reusable macro that Loki exports. I've also piggybacked a small fix to the fypp line number annotation sanitization.
> Reusable cmake macro to update target sources

- loki/transformations/build_system/module_wrap.py
- loki/transformations/build_system/tests/test_dependency.py
A small PR to fix the `replace_ignore_items` option in the `ModuleWrapTransformation`.
> MODULE_WRAP: fix bug in `replace_ignore_items` option

- loki/transformations/remove_code.py
- loki/transformations/tests/test_remove_code.py
This PR adds the ability to optionally remove unused arguments from a call-tree. A single reverse pass is used, which means the `Subroutine` signature is updated before the `CallStatement`. That's why `call.arg_map` isn't used but rather the order of the arguments is relied upon to map unused dummy arguments to arguments.
> Remove unused arguments in a call-tree

- loki/expression/tests/test_expression.py
- loki/frontend/fparser.py
- loki/frontend/omni.py
- loki/subroutine.py
- loki/tests/test_subroutine.py
- loki/transformations/sanitise/tests/test_associates.py
~_Note: Sits on top of #543 out of sheer laziness, but should address #195._~
Another housekeeping PR that removes a remnant from the past. This little hack lived in the constructor of subroutines and is no longer needed, I think. I've run this with ecphys regression, and everything is fine, so I would like to remove it instead of re-implementing, as suggested in #195.
> Subroutine: Remove automatic derivation of shape from ALLOCATE

- loki/dimension.py
- loki/transformations/single_column/base.py
- loki/transformations/single_column/demote.py
- loki/transformations/single_column/devector.py
- loki/transformations/single_column/revector.py
- loki/transformations/single_column/tests/test_scc.py
- loki/transformations/single_column/tests/test_scc_hoist.py
This PR includes the following fixes/updates to the identification of SCC separator nodes:
- Vector inline calls, typically an array reduction intrinsic like `SUM`, are now marked as separator nodes
- Pointer association to a horizontal array target is also marked as a separator node
- Explicit `!$loki separator` pragmas can now be placed at an arbitrary nesting depth inside a subroutine body
- Explicit `!$loki vector-reduction` pragmas can now be placed at an arbitrary nesting depth inside a subroutine body
- An exception is now raised when an explicit `!$loki vector-reduction` pragma is discovered during an SCCSeq transformation
> Various fixes to SCC separator nodes 

- docs/source/loki_pragma_model.csv
- loki/transformations/data_offload/offload.py
- loki/transformations/pragma_model.py
- loki/transformations/tests/test_pragma_model.py
'loki device-present' only for execution on device which is not mapped for OpenMP, 'loki structured-data present(...)' on host mapped for both OpenACC and OpenMP
> change behaviour for 'device-present' pragmas

- .github/workflows/regression_tests.yml
- .github/workflows/tests.yml
The download of OpenJDK in the dependency installation for OMNI failed spuriously but increasingly often in the last two days. This replaces the installation of the JDK by the official setup-java action, which is hopefully more robust and independent from the runner image.
> Hotfix for GH Actions: Replace package distribution version of JDK with setup-java action

- loki/frontend/fparser.py
- loki/tests/test_sourcefile.py
- loki/tests/test_subroutine.py
Another small housekeeping PR that aims to tidy up the construction of `Subroutine` and `Module` objects in the FParser frontend. The key changes are a slight generalisation of utilities to move comments between spec and body, and a common utility to pre-instantiate sub-procedure scopes.
_As a bonus, this gets rid of the last use of a naked dict-based `Transformer` in the AST traversal._ 
To make this safer, I also extended one of the `Subroutine` tests to capture the corner case that forces us to pre-instantiate internal and module procedures. We do this, so that all subroutines are created up front, so that `InlineCall`s between two internal routines are handled cleanly and the cross-calling type info is generated safely.
I also piggy-backed a small change that makes sure we use the …
> FParser: Better `Subroutine` and `Module` construction

- docs/source/loki_pragma_model.csv
- loki/transformations/data_offload/global_var.py
- loki/transformations/data_offload/tests/test_global_var.py
- loki/transformations/pragma_model.py
Having:
```fortran
module some_mod
integer, allocatable :: foo(:, :)
!$omp declare target(foo)
end module some_mod
```
Unfortunately, this doesn't work:
```fortran
use some_mod, only: foo
!$omp target update to(foo)
```
However, the following works (as workaround):
```fortran
use some_mod, only: foo
!$omp target update to(foo)
!$omp target enter data map(to: foo)
```
> hack for OpenMP updating global variables on device

- loki/transformations/single_column/annotate.py
- loki/transformations/single_column/revector.py
- loki/transformations/single_column/tests/test_scc.py
Derived-types are classified as "aggregate variables" in the OpenACC and OpenMP offload standards and have the same implicit data attributes as arrays. This PR therefore extends `SCCAnnotate` to also privatise derived-type scalars (derived-type arrays would have already been privatised according to the existing implementation).
Other changes included are:
- Skip driver loop labeling for loops with existing parallel pragmas
- The ability to use a derived-type component to set the vector_length in a gang loop
> SCC: privatise derived-type scalars

- loki/transformations/single_column/annotate.py
- loki/transformations/single_column/tests/test_scc.py
This cause trouble in EC-physics, as we rely on them being treated as globals in various places. So, by default we leave this option off for now, until this is tested further.
As a bonus, this also replaces a use of `set` for unique variable lists with `dict.fromkeys()` to ensure reproducible string output in the list of private variable names.
This PR should bring EC-physics regression back to green.
> SCC: Make privatising derived-type variables configurable

- loki/analyse/analyse_dataflow.py
- loki/analyse/tests/test_analyse_dataflow.py
- loki/transformations/data_offload/tests/test_global_var.py
This PR fixes the following bugs in the dataflow analysis:
- Stripping dimensions of nested derived-type accesses
- Extending the exclusion of memory status checking calls to loop bounds
The PR also includes a behaviour change. Previously, all parents of a derived-type expression were marked as used if a single type member was used. Now, only the full derived-type expression is included in the used symbols set. For example, the `used_symbols` for the assignment `D = A%B%C` will be limited to `A%B%C`, whereas previously it would have also included `A%B, A`.
> Small bug fixes in the `DataflowAnalysis`

- docs/source/loki_pragma_model.csv
- loki/transformations/data_offload/tests/test_field_offload.py
- loki/transformations/field_api.py
- loki/transformations/pragma_model.py
- loki/transformations/tests/test_pragma_model.py
This small PR contributes the following offload utilities:
- `attach/detach` clauses for OpenACC unstructured data pragmas
- Optional `finalize` clause for OpenACC unstructured data pragmas
- Addition of `GET_HOST_DATA_*` and `DELETE_DEVICE_DATA`
> Add offload utils

- loki/batch/tests/test_scheduler.py
- loki/batch/tests/test_transformation.py
- loki/batch/transformation.py
- loki/frontend/omni.py
- loki/transformations/inline/tests/test_inline_transformation.py
- loki/transformations/single_column/tests/test_scc.py
- loki/transformations/tests/test_block_index_inject.py
This should give a slightly more informative message when hitting an exception in a transformation, giving an indication on what program unit node the problem occurs.
> Basic exception handling with some origin information for Transformation.apply

- loki/transformations/data_offload/__init__.py
- loki/transformations/data_offload/offload_deepcopy.py
- loki/transformations/data_offload/tests/test_offload_deepcopy.py
- loki/transformations/single_column/annotate.py
This PR contributes an analysis pass to determine the nested usage of arguments to a call-tree. The result is a nested dict per driver-loop containing the access mode of arguments to all the target routines in that driver loop. Three access modes are possible: `read, write, readwrite`. The companion to this analysis is a transformation to generate deepcopy data offload instructions based on the analysis.
The analysis relies on a reversed traversal of the scheduler tree, but the accompanying transformation does not traverse the scheduler tree, and instead just operates at the driver layer using the collected analysis. Clearly, some level of configurability is necessary in the deepcopy generation, for example for inconsistent naming conventions in type definitions. The best way I could …
> `DataOffloadDeepcopyAnalysis`

- docs/source/loki_pragma_model.csv
- loki/tests/sources/projHoist/module/driver_mod.f90
- loki/tests/sources/projHoist/module/subroutines_mod.f90
- loki/transformations/pragma_model.py
- loki/transformations/single_column/hoist.py
- loki/transformations/single_column/revector.py
- loki/transformations/single_column/tests/test_scc.py
- loki/transformations/single_column/tests/test_scc_hoist.py
- loki/transformations/temporaries/hoist_variables.py
- loki/transformations/temporaries/tests/test_hoist_variables.py
- loki/transformations/utilities.py
A bugfix PR that contributes the following fixes:
- Variable kind specifiers are hoisted as necessary with temporaries
- `get_integer_variable` can now also return a type-bound integer
- Pointers/allocatable temporaries are no longer hoisted
- Already hoisted temporaries are now filtered by name, to avoid repetitions when bounds aliases are used
- The finalize clause is added to the device deletion of hoisted temporaries. This shouldn't be necessary, and likely points to an nvhpc openacc runtime bug.
- SCCRevector can now also used dimension configs with bounds declared in upper-case
> Various `SCCHoist` fixes

- loki/batch/item.py
- loki/batch/item_factory.py
- loki/program_unit.py
- loki/transformations/inline/tests/test_inline_transformation.py
- loki/transformations/inline/transformation.py
Inline Trafo CMake planing when inlining marked routines.
In the planning step:
* look for calls with and without `!$loki inline` pragmas
* adapt `removed_dependencies` and `additional_dependencies` according to which calls are inlined
> Inline Trafo CMake planing when inlining marked routines

- loki/backend/__init__.py
- loki/backend/cufgen.py
- loki/backend/fgen.py
- loki/backend/fgencon.py
- loki/backend/tests/test_conservative.py
- loki/frontend/fparser.py
- loki/frontend/regex.py
- loki/frontend/source.py
- loki/frontend/tests/test_fparser_source.py
- loki/ir/expr_visitors.py
- loki/ir/tests/test_expr_visitors.py
- loki/ir/tests/test_transformer.py
- loki/ir/transformer.py
- loki/lint/tests/test_linter.py
- loki/lint/utils.py
- loki/program_unit.py
- loki/sourcefile.py
~_Integration note: This is based on top of PR #524 and needs to be reviewed/merged after._~
This PR brings in a rudimentary rethink of the "conservative" `fgen` option that is based on a dedicated backend visitor that aims to re-create as much of the original source string as possible. The purpose of this is to then create string output that only captures the changes to the IR/expression tree in comparison to the originally parsed source, which would allow us to generate reasonably a diff/patch when comparing to the original file. **Please note that this is not yet far enough for diff-generation(!) in all cases**, but provides a first set of changes that can recapture a significant amount the original source (eg. non-conformant indentation).
In particular, up to now, we hard-invalidated …
> Backend: New generalised "string-conservative" FGen backend

- loki/transformations/data_offload/offload_deepcopy.py
- loki/transformations/data_offload/tests/test_offload_deepcopy.py
A small bugfix for the deepcopy generation for nested pointers to derived-types.
> Deepcopy bugfix for pointers to derived-types

- loki/expression/__init__.py
- loki/expression/evaluation.py
- loki/expression/parser.py
- loki/expression/symbolic.py
- loki/expression/tests/test_parser.py
- loki/expression/tests/test_symbolic.py
Some fixes and extensions.
Moreover, the old approach when evaluating an expression was:
> "parse expression to pymbolic symbols (with some Loki symbols enhanced)" -> "evaluate this expression (as far as possible)" -> "convert pymbolic symbols to Loki symbols"
With this PR it is now possible to:
> "parse expression to pymbolic symbols (with some Loki symbols enhanced)" -> "convert pymbolic symbols to Loki symbols" -> "evaluate this expression being Loki symbols (as far as possible)"
So the plan would be to (either now or later) remove `LokiPymbolicEvaluationMapper` and further improve and extend `LokiEvaluationMapper`.
> improve, extend and move `LokiEvaluationMapper`

- loki/transformations/remove_code.py
- loki/transformations/single_column/scc.py
- loki/transformations/tests/test_remove_code.py
optionally only arrays.
Either via `do_remove_unused_vars(routine, remove_only_arrays=True/False)` or via `RemoveCodeTransformation(remove_unused_vars=True, remove_only_arrays=True/False)`.
> New utility within 'remove_code': remove unused temporaries/locals

- loki/expression/__init__.py
- loki/expression/literals.py
- loki/expression/mixins.py
- loki/expression/operations.py
- loki/expression/symbols.py
- loki/expression/tests/test_parser.py
- loki/expression/tests/test_symbols.py
A small housekeeping PR that moves various symbol definitions in our expression sub-package in further sub-packages, enforces the strict usage of the `StrComparisonMixin` throughout and adds some property tests for the most commonly used symbols. This is aimed at a more thorough re-design of expression symbols towards future pymbolic compatibility.
In particular, reorganisation does:
* Makes all symbols strictly adhere to string-comparison via the `StrCompareMixin`
* Moves `StrCompareMixin` and its utility metheod into `loki.expressions.mixins`
* Moves algebraic and technical operations over to the existing `loki.expressions.operations`
* Moves all literal class definitions to `loki.expressions.mixins`
* Exposes all literals and operations via imports in `loki.expression.symbols`, so that …
> Expression: Small re-organisation and moar tests

- loki/transformations/single_column/scc.py
The order was wrong in a few pipelines, which could lead to spurious declarations of privatised variables during the annotate step, that are then removed subsequently.
> SCC: Apply Annotate after RemoveUnusedVars

- loki/batch/configure.py
- loki/tests/test_cmake.py
- pyproject.toml
Hi,
This replace usage of the old `toml` library from the Python2 era with the newer & maitained `tomli` & `tomli_w` couple.
https://wiki.debian.org/Python/Backports
Later when support for obsolete Python3 versions is dropped, `tomli` can be replaced with builtin ``tomllib`
> replace ancient "toml" with newer "tomli"/"tomli_w" couple

- loki/transformations/remove_code.py
- loki/transformations/tests/test_remove_code.py
This PR adds additional options to the `do_remove_marked_regions` utility and associated transformation, so that we may inject "abort" calls into unsupported code regions. The new mechanics allow specifying a subroutine name to call and an optional message string that gets passed as the single argument. A third option then allows the insertion of a ~C-import~ module import, which only gets performed if a substitution has happened.
~Note, I'm filing this as draft, as I have not tested this in a full setup yet.~
> Transformation: Add "replacement call" mechanics to marked region code removal 

- loki/transformations/sanitise/associates.py
- loki/transformations/sanitise/tests/test_associates.py
edge case with some ambiguity wasn't resolved correctly:
```fortran
ASSOCIATE (ndim=>some_obj%ndim, nested_obj=>other_obj%nested)
CALL some_func(nested_obj%ndim)
END ASSOCIATE
```
do_resolve_associates ...
```fortran
CALL some_func(some_obj%ndim)
```
which is obviously wrong and fixed with this PR to produce 
```fortran
CALL some_func(other_obj%nested%ndim)
```
> fix resolve associates
